#include "MAIN/MainCanonicalStateV4ExactFacts.h"

#include <stdio.h>
#include <string.h>
#define CHECK(x) do { if (!(x)) { fprintf(stderr, "%d: %s\n", __LINE__, #x); return 1; } } while (0)

struct Fixture { struct NativeMatchConfigV1 config; struct MainCanonicalStateV4Context context; struct NativeIdentityV1 identity; struct NativeCanonicalControlV1 control; struct NativeCanonicalRngV1 retail; struct NativeDeterministicRngBankV1 rng; struct NativeCanonicalInputV1 input; struct NativeCanonicalDriversDetailedV1 drivers; struct NativeCanonicalWorldCountersV1Facts counters; struct NativeCanonicalWorldMineRegistryV1Facts mines; struct MainCanonicalTopologyFacts topology; struct MainCanonicalTopologyQuadCheckpointFact quad[1]; struct MainCanonicalTopologyRestartFact restart[1]; };
static int Init(struct Fixture *f) {
	NativeMatchConfigV1_InitArcadeTwoCab(&f->config); f->config.trackID=7; f->config.gameMode1=2; f->config.gameMode2=3; f->config.rules=4; f->config.lapCount=3; f->config.tickRateNumerator=30; f->config.tickRateDenominator=1; f->config.masterSeed=UINT64_C(0x123456789abcdef0);
	for(uint32_t i=0;i<32;i++){f->config.buildIdentity[i]=(uint8_t)(0x10+i);f->config.contentIdentity[i]=(uint8_t)(0x80+i);f->config.botRulesDigest[i]=(uint8_t)(0x40+i);} for(uint32_t i=0;i<6;i++){f->config.slots[i].characterID=(uint8_t)i;f->config.slots[i].difficulty=2;}
	if(!NativeMatchConfigV1_Validate(&f->config)||!MainCanonicalStateV4Context_Init(&f->context,&f->config)||!NativeDeterministicRngBankV1_Init(&f->rng,f->config.masterSeed,f->config.rngDerivationVersion))return 0;
	memcpy(f->identity.build,f->config.buildIdentity,32);memcpy(f->identity.content,f->config.contentIdentity,32);f->input.padCount=NATIVE_CANONICAL_INPUT_PAD_COUNT;f->input.pads[0].connected=1;
	NativeCanonicalDriversDetailedV1_Init(&f->drivers); f->drivers.prelude.presenceMask=1;f->drivers.prelude.playerCount=1;f->drivers.prelude.humanPlayerPositions[0]=0;f->drivers.prelude.raceOrderCount=1;f->drivers.prelude.raceOrder[0]=0;f->drivers.prelude.numLaps=3;f->drivers.slots[0].meta.present=1;f->drivers.slots[0].meta.slotIndex=0;f->drivers.slots[0].meta.driverID=5;f->drivers.slots[0].meta.characterID=7;f->drivers.slots[0].meta.driverKind=NATIVE_CANONICAL_DRIVER_KIND_HUMAN;f->drivers.slots[0].meta.kartState=2;f->drivers.slots[0].meta.actionsFlagSet=UINT32_C(0x11223344);f->drivers.slots[0].meta.numWumpas=-4;f->drivers.slots[0].race.clockReceive=-5;f->drivers.slots[0].race.invincibleTimer=-6;f->drivers.slots[0].physics.currQuadIndex=UINT32_C(0x55667788);f->drivers.slots[0].physics.velocity[1]=-7;f->drivers.slots[0].physics.rotCurr[3]=-8;f->drivers.slots[0].dynamics.field[NATIVE_CANONICAL_DRIVER_DYN_SPEED]=9;f->drivers.slots[0].dynamics.zSpeed=-10;
	f->topology.flags=NATIVE_CANONICAL_TOPOLOGY_FLAG_AVAILABLE;f->topology.levelID=-7;f->quad[0].restartIndex=0;f->restart[0].edgeIndex[0]=NATIVE_CANONICAL_TOPOLOGY_RESTART_ABSENT;f->restart[0].edgeIndex[1]=NATIVE_CANONICAL_TOPOLOGY_RESTART_ABSENT;f->restart[0].edgeIndex[2]=NATIVE_CANONICAL_TOPOLOGY_RESTART_ABSENT;f->restart[0].edgeIndex[3]=NATIVE_CANONICAL_TOPOLOGY_RESTART_ABSENT;f->topology.quadCheckpoints.items=f->quad;f->topology.quadCheckpoints.count=1;f->topology.restarts.items=f->restart;f->topology.restarts.count=1;
	return NativeCanonicalDriversDetailedV1_Validate(&f->drivers);
}
static int Project(struct NativeCanonicalStateV4 *out,const struct Fixture *f,uint8_t *scratch,size_t n){return MainCanonicalState_ProjectV4FromExactFacts(out,&f->context,&f->identity,41,&f->control,&f->retail,&f->rng,&f->input,&f->drivers,&f->counters,&f->mines,&f->topology,scratch,n);}
static int Reference(struct NativeCanonicalStateV4 *out,const struct Fixture *f,uint8_t *scratch){struct NativeCanonicalDriversV1 d;struct NativeCanonicalWorldCountersV1 c;struct NativeCanonicalWorldMineRegistryV1 m;struct NativeCanonicalTopologyV1 t;return NativeCanonicalDriversDetailedV1_BuildSummaryWithScratch(&f->drivers,scratch,NATIVE_CANONICAL_DRIVERS_NORMATIVE_BYTES,&d)&&NativeCanonicalWorldCountersV1_FromFacts(&c,&f->counters)&&NativeCanonicalWorldMineRegistryV1_FromFacts(&m,&f->mines)&&MainCanonicalTopologyFacts_ToV1(&f->topology,&t)&&MainCanonicalState_ProjectV4(out,&f->context,&f->identity,41,&f->control,&f->retail,&f->rng,&f->input,&d,&c,&m,&t);}
static uint32_t Domains(const struct NativeCanonicalStateV4 *a,const struct NativeCanonicalStateV4 *b){uint32_t m=0;for(uint32_t i=0;i<NATIVE_CANONICAL_DOMAIN_COUNT;i++)if(a->domainDigests[i]!=b->domainDigests[i])m|=1u<<i;return m;}
int main(void){struct Fixture f,x;struct NativeCanonicalStateV4 base,state,reference,before;uint8_t scratch[NATIVE_CANONICAL_DRIVERS_NORMATIVE_BYTES],scratch2[NATIVE_CANONICAL_DRIVERS_NORMATIVE_BYTES];memset(&f,0,sizeof(f));CHECK(Init(&f));CHECK(Project(&base,&f,scratch,sizeof(scratch))&&Reference(&reference,&f,scratch2)&&memcmp(&base,&reference,sizeof(base))==0);
	x=f;x.drivers.slots[0].meta.driverID=1;CHECK(Project(&state,&x,scratch,sizeof(scratch))&&Domains(&base,&state)==8);x=f;x.counters.flags=1;x.counters.activeBombMissileCount=1;CHECK(Project(&state,&x,scratch,sizeof(scratch))&&Domains(&base,&state)==16);x=f;x.mines.flags=1;x.mines.activeCapacity=1;x.mines.records[0].state=0;x.mines.records[0].queueRank=0xff;CHECK(Project(&state,&x,scratch,sizeof(scratch))&&Domains(&base,&state)==16);x=f;x.topology.levelID=-6;CHECK(Project(&state,&x,scratch,sizeof(scratch))&&Domains(&base,&state)==32);
	/* Exact zero facts remain exact unavailable WORLD/TOPOLOGY values. */ x=f;memset(&x.topology,0,sizeof(x.topology));CHECK(Project(&state,&x,scratch,sizeof(scratch))&&state.worldCounters.flags==0&&state.worldCounters.activeBombMissileCount==0&&state.mineRegistry.flags==0&&state.topology.flags==0&&Domains(&base,&state)==32);
	before=base;x=f;x.drivers.prelude.slotCount=0;CHECK(!Project(&before,&x,scratch,sizeof(scratch))&&memcmp(&before,&base,sizeof(base))==0);x=f;x.counters.flags=1;x.counters.activeBombMissileCount=99;CHECK(!Project(&before,&x,scratch,sizeof(scratch))&&memcmp(&before,&base,sizeof(base))==0);x=f;x.mines.flags=1;x.mines.activeCapacity=1;x.mines.records[0].state=1;x.mines.records[0].queueRank=1;CHECK(!Project(&before,&x,scratch,sizeof(scratch))&&memcmp(&before,&base,sizeof(base))==0);x=f;x.topology.flags=0;CHECK(!Project(&before,&x,scratch,sizeof(scratch))&&memcmp(&before,&base,sizeof(base))==0);CHECK(!Project(&before,&f,NULL,sizeof(scratch))&&memcmp(&before,&base,sizeof(base))==0);CHECK(!Project(&before,&f,scratch,sizeof(scratch)-1)&&memcmp(&before,&base,sizeof(base))==0);CHECK(!MainCanonicalState_ProjectV4FromExactFacts(&before,&f.context,&f.identity,1,&f.control,&f.retail,&f.rng,&f.input,NULL,&f.counters,&f.mines,&f.topology,scratch,sizeof(scratch))&&memcmp(&before,&base,sizeof(base))==0);CHECK(!MainCanonicalState_ProjectV4FromExactFacts(&before,&f.context,&f.identity,1,&f.control,&f.retail,&f.rng,&f.input,&f.drivers,NULL,&f.mines,&f.topology,scratch,sizeof(scratch))&&memcmp(&before,&base,sizeof(base))==0);CHECK(!MainCanonicalState_ProjectV4FromExactFacts(&before,&f.context,&f.identity,1,&f.control,&f.retail,&f.rng,&f.input,&f.drivers,&f.counters,NULL,&f.topology,scratch,sizeof(scratch))&&memcmp(&before,&base,sizeof(base))==0);CHECK(!MainCanonicalState_ProjectV4FromExactFacts(&before,&f.context,&f.identity,1,&f.control,&f.retail,&f.rng,&f.input,&f.drivers,&f.counters,&f.mines,NULL,scratch,sizeof(scratch))&&memcmp(&before,&base,sizeof(base))==0);CHECK(!MainCanonicalState_ProjectV4FromExactFacts(NULL,&f.context,&f.identity,1,&f.control,&f.retail,&f.rng,&f.input,&f.drivers,&f.counters,&f.mines,&f.topology,scratch,sizeof(scratch)));
	/* Relocating borrowed fact ranges does not alter canonical output. */ { struct MainCanonicalTopologyQuadCheckpointFact q[1];struct MainCanonicalTopologyRestartFact r[1];x=f;q[0]=f.quad[0];r[0]=f.restart[0];x.topology.quadCheckpoints.items=q;x.topology.restarts.items=r;CHECK(Project(&state,&x,scratch,sizeof(scratch))&&memcmp(&state,&base,sizeof(state))==0); }
	puts("main_canonical_state_v4_exact_facts_test: passed");return 0;}
