file(READ "${CMAKE_CURRENT_LIST_DIR}/../CMakeLists.txt" cmake)
foreach(forbidden IN ITEMS ctr_native_canonical_runtime ctr_native_replay_scheduler_v4 ctr_native_replay_v4_file)
    string(REGEX MATCH "target_link_libraries\\(${forbidden}[^)]*ctr_native_canonical_exact_domains_v4" hit "${cmake}")
    if(hit)
        message(FATAL_ERROR "main_canonical_state_v4_exact_facts_isolation: ${forbidden} must not link the exact-facts adapter")
    endif()
endforeach()
string(REGEX MATCH "target_link_libraries\\(ctr_native[ \\t][^)]*ctr_native_canonical_exact_domains_v4" executable_hit "${cmake}")
if(executable_hit)
    message(FATAL_ERROR "main_canonical_state_v4_exact_facts_isolation: game executable must not link the exact-facts adapter")
endif()
file(READ "${CMAKE_CURRENT_LIST_DIR}/../game/MAIN/MainCanonicalStateV4ExactFacts.c" source)
foreach(forbidden IN ITEMS Extract gGT sdata D231 Level MainMain Runtime Scheduler Replay Network UI)
    string(FIND "${source}" "${forbidden}" found)
    if(NOT found EQUAL -1)
        message(FATAL_ERROR "main_canonical_state_v4_exact_facts_isolation: forbidden source token ${forbidden}")
    endif()
endforeach()
