#include "MAIN/MainArcadeBotTickEvidence.h"
#include <stdio.h>
#include <string.h>
#define CHECK(x) do { if (!(x)) { fprintf(stderr,"fail %d: %s\n",__LINE__,#x); return 1; } } while (0)
struct Inputs { struct NativeMatchConfigV1 config; struct MainArcadeBotSetupPlan plan; struct NativeCanonicalDriverSlotV1 before,after; struct NativeDeterministicRngBankV1 rngBefore,rngAfter; };
static int Same(const void *a,const void *b,size_t n){return memcmp(a,b,n)==0;}
static int Make(struct Inputs *in)
{
	uint64_t draw; memset(in,0,sizeof(*in)); NativeMatchConfigV1_InitArcadeTwoCab(&in->config); in->config.trackID=7;in->config.gameMode1=8;in->config.gameMode2=9;in->config.rules=10;in->config.lapCount=3;in->config.tickRateNumerator=30;in->config.tickRateDenominator=1;in->config.masterSeed=9;
	for(uint8_t i=0;i<8;i++)if(in->config.slots[i].role!=NATIVE_MATCH_SLOT_ROLE_INACTIVE){in->config.slots[i].characterID=(uint8_t)(i+1);in->config.slots[i].difficulty=(uint8_t)(20+i);}memset(in->config.buildIdentity,1,32);memset(in->config.contentIdentity,2,32);memset(in->config.botRulesDigest,3,32);
	if(!NativeMatchConfigV1_Validate(&in->config)||!NativeDeterministicRngBankV1_Init(&in->rngBefore,in->config.masterSeed,in->config.rngDerivationVersion))return 0;in->rngAfter=in->rngBefore;if(!NativeDeterministicRngBankV1_NextU64(&in->rngAfter,NATIVE_DETERMINISTIC_RNG_STREAM_BOT,2,2,&draw))return 0;
	in->plan.profile=in->config.profile;in->plan.botMask=UINT32_C(0x3c);in->plan.botCount=4;in->plan.locked=1;if(!NativeMatchConfigV1_Digest(&in->config,in->plan.matchConfigDigest)||!NativeDeterministicRngBankV1_Digest(&in->rngBefore,in->plan.rngBeforeDigest)||!NativeDeterministicRngBankV1_Digest(&in->rngAfter,in->plan.rngAfterDigest))return 0;
	for(uint8_t s=2;s<=5;s++){struct MainArcadeBotSetupAssignment *a=&in->plan.assignments[s];a->enabled=1;a->stableSlot=s;a->nativeDriverSlot=s;a->characterID=in->config.slots[s].characterID;a->difficulty=in->config.slots[s].difficulty;a->spawnOrder=s;a->navPathIndex=(uint8_t)(s%3);a->accelerationOrder=s;a->setupSequence=(uint8_t)(s-2);a->setupRandom=s;}
	in->before.meta.present=1;in->before.meta.slotIndex=2;in->before.meta.driverKind=NATIVE_CANONICAL_DRIVER_KIND_BOT;in->before.meta.behaviorID=1;in->before.meta.threadBehaviorID=NATIVE_CANONICAL_DRIVER_THREAD_BOTS_DRIVE;in->before.bot.botPath=0;in->after=in->before;in->after.bot.botNavFrameIndex=1;return 1;
}
static int Build(const struct Inputs *in,struct MainArcadeBotTickEvidenceV1 *out){return MainArcadeBotTickEvidenceV1_Build(out,77,2,&in->config,&in->plan,&in->before,&in->after,&in->rngBefore,&in->rngAfter);}
int main(void)
{
	struct Inputs in,bad;struct MainArcadeBotTickEvidenceV1 e,d,old;uint8_t bytes[MAIN_ARCADE_BOT_TICK_EVIDENCE_V1_ENCODED_BYTES],digest[32],configDigest[32];struct NativeCodecWriter w;struct NativeCodecReader r;uint64_t draw;
	CHECK(Make(&in));CHECK(Build(&in,&e));CHECK(MainArcadeBotTickEvidenceV1_Validate(&e));CHECK(NativeMatchConfigV1_Digest(&in.config,configDigest));CHECK(Same(e.configDigest,configDigest,32));CHECK(Same(e.botRulesDigest,in.config.botRulesDigest,32));CHECK(e.botDrawCountBefore==0&&e.botDrawCountAfter==1);NativeCodecWriter_Init(&w,bytes,sizeof(bytes),NULL);CHECK(MainArcadeBotTickEvidenceV1_Encode(&w,&e)&&w.offset==sizeof(bytes));{static const uint8_t golden[12]={0x45,0x42,0x54,0x31,0x01,0,0,0,0x4d,0,0,0};CHECK(Same(bytes,golden,sizeof(golden)));}NativeCodecReader_Init(&r,bytes,sizeof(bytes));CHECK(MainArcadeBotTickEvidenceV1_Decode(&r,&d)&&Same(&e,&d,sizeof(e)));CHECK(MainArcadeBotTickEvidenceV1_Digest(&e,digest));
	old=d;bytes[0]^=1;NativeCodecReader_Init(&r,bytes,sizeof(bytes));CHECK(!MainArcadeBotTickEvidenceV1_Decode(&r,&d)&&Same(&d,&old,sizeof(d))&&r.offset==0);bytes[0]^=1;old=d;bytes[4]^=1;NativeCodecReader_Init(&r,bytes,sizeof(bytes));CHECK(!MainArcadeBotTickEvidenceV1_Decode(&r,&d)&&Same(&d,&old,sizeof(d))&&r.offset==0);bytes[4]^=1;old=d;bytes[200]^=1;NativeCodecReader_Init(&r,bytes,sizeof(bytes));CHECK(!MainArcadeBotTickEvidenceV1_Decode(&r,&d)&&Same(&d,&old,sizeof(d))&&r.offset==0);bytes[200]^=1;
	bad=in;bad.config.lapCount=0;old=e;CHECK(!Build(&bad,&e)&&Same(&e,&old,sizeof(e)));bad=in;bad.config.slots[2].role=NATIVE_MATCH_SLOT_ROLE_CAB1_HUMAN;CHECK(!Build(&bad,&e));bad=in;bad.plan.assignments[2].stableSlot=3;CHECK(!Build(&bad,&e));bad=in;bad.plan.assignments[2].enabled=0;CHECK(!Build(&bad,&e));bad=in;bad.plan.botMask^=UINT32_C(1)<<2;CHECK(!Build(&bad,&e));bad=in;bad.plan.rngAfterDigest[0]^=1;CHECK(!Build(&bad,&e));bad=in;bad.rngAfter.masterSeed++;CHECK(!Build(&bad,&e));bad=in;CHECK(NativeDeterministicRngBankV1_NextU64(&bad.rngAfter,NATIVE_DETERMINISTIC_RNG_STREAM_ITEMS,NATIVE_DETERMINISTIC_RNG_GLOBAL_SLOT,NATIVE_DETERMINISTIC_RNG_GLOBAL_SLOT,&draw));CHECK(!Build(&bad,&e));bad=in;CHECK(NativeDeterministicRngBankV1_NextU64(&bad.rngAfter,NATIVE_DETERMINISTIC_RNG_STREAM_BOT,3,3,&draw));CHECK(!Build(&bad,&e));bad=in;CHECK(NativeDeterministicRngBankV1_NextU64(&bad.rngAfter,NATIVE_DETERMINISTIC_RNG_STREAM_BOT,2,2,&draw));CHECK(NativeDeterministicRngBankV1_Digest(&bad.rngAfter,bad.plan.rngAfterDigest));CHECK(Build(&bad,&e));bad=in;bad.config.botRulesDigest[0]^=1;CHECK(!Build(&bad,&e));CHECK(NativeMatchConfigV1_Digest(&bad.config,bad.plan.matchConfigDigest));CHECK(Build(&bad,&e)&&Same(e.botRulesDigest,bad.config.botRulesDigest,32));CHECK(!MainArcadeBotTickEvidenceV1_Build(NULL,77,2,&in.config,&in.plan,&in.before,&in.after,&in.rngBefore,&in.rngAfter));return 0;
}
