file(READ "${CMAKE_CURRENT_LIST_DIR}/../CMakeLists.txt" cmake)
set(target ctr_native_main_canonical_topology_layout_contract_probe)

string(FIND "${cmake}" "add_library(${target} OBJECT" target_declaration)
string(FIND "${cmake}" "tests/main_canonical_topology_layout_contract_probe.c" probe_source)
if(target_declaration EQUAL -1 OR probe_source EQUAL -1)
    message(FATAL_ERROR "topology layout contract: missing compile-probe target declaration")
endif()

string(REGEX MATCH "target_link_libraries\\([ \\t\\r\\n]*${target}[^)]*\\)" target_link "${cmake}")
if(target_link)
    message(FATAL_ERROR "topology layout contract: compile probe must not link a library")
endif()

foreach(forbidden_consumer IN ITEMS ctr_native ctr_native_canonical_runtime ctr_native_replay_scheduler_v4 ctr_native_replay_v4 ctr_native_replay_v4_file ctr_native_canonical_topology ctr_native_canonical_topology_facts)
    string(REGEX MATCH "target_link_libraries\\([ \\t\\r\\n]*${forbidden_consumer}[^)]*${target}" bad_consumer "${cmake}")
    if(bad_consumer)
        message(FATAL_ERROR "topology layout contract: ${forbidden_consumer} must not consume the compile probe")
    endif()
endforeach()

set(contract_header "${CMAKE_CURRENT_LIST_DIR}/../game/MAIN/MainCanonicalTopologyLayoutContract.h")
set(probe_source "${CMAKE_CURRENT_LIST_DIR}/main_canonical_topology_layout_contract_probe.c")
file(READ "${contract_header}" header_text)
file(READ "${probe_source}" probe_text)

string(REGEX MATCHALL "#[ \\t]*include[ \\t]+<[^>]+>" header_includes "${header_text}")
if(NOT "${header_includes}" STREQUAL "#include <common.h>;#include <platform/native_topology_asset_layout.h>")
    message(FATAL_ERROR "topology layout contract: public header include boundary changed")
endif()
string(REGEX MATCHALL "#[ \\t]*include[ \\t]+\"[^\"]+\"" header_quoted_includes "${header_text}")
if(header_quoted_includes)
    message(FATAL_ERROR "topology layout contract: public header must not include game adapters")
endif()

foreach(forbidden IN ITEMS MainMain Runtime Extract Fact Adapter Scheduler Replay Network Socket Recv Send UI Project "extern ")
    string(FIND "${header_text}" "${forbidden}" forbidden_offset)
    if(NOT forbidden_offset EQUAL -1)
        message(FATAL_ERROR "topology layout contract: forbidden header token ${forbidden}")
    endif()
endforeach()

if(NOT probe_text STREQUAL "#include \"MAIN/MainCanonicalTopologyLayoutContract.h\"\n\nint main(void)\n{\n\treturn 0;\n}\n")
    message(FATAL_ERROR "topology layout contract: compile probe must stay declaration-only")
endif()
