file(READ "${CMAKE_CURRENT_LIST_DIR}/../CMakeLists.txt" cmake)
set(target main_canonical_topology_lease_authority)
string(FIND "${cmake}" "add_library(${target} STATIC" declared)
if(declared EQUAL -1)
    message(FATAL_ERROR "topology lease authority: missing isolated leaf target")
endif()
string(REGEX MATCH "target_link_libraries\\(${target}[ \\t\\r\\n]+([^)]*)\\)" links "${cmake}")
if(NOT links)
    message(FATAL_ERROR "topology lease authority: missing direct dependency declaration")
endif()
set(deps "${CMAKE_MATCH_1}")
string(REGEX MATCHALL "[A-Za-z0-9_]+" deps "${deps}")
list(REMOVE_ITEM deps "" PUBLIC PRIVATE INTERFACE)
if(NOT "${deps}" STREQUAL "ctr_native_topology_residency")
    message(FATAL_ERROR "topology lease authority: unexpected direct dependencies: ${deps}")
endif()
foreach(consumer IN ITEMS ctr_native ctr_native_canonical_runtime ctr_native_replay_scheduler_v4 ctr_native_replay_v4 ctr_native_replay_v4_file ctr_native_canonical_topology)
    string(REGEX MATCH "target_link_libraries\\(${consumer}[^)]*${target}" hit "${cmake}")
    if(hit)
        message(FATAL_ERROR "topology lease authority: ${consumer} must not consume dormant leaf")
    endif()
endforeach()
file(READ "${CMAKE_CURRENT_LIST_DIR}/../game/MAIN/MainCanonicalTopologyLeaseAuthority.h" header)
file(READ "${CMAKE_CURRENT_LIST_DIR}/../game/MAIN/MainCanonicalTopologyLeaseAuthority.c" source)
foreach(unit IN ITEMS header source)
    foreach(forbidden IN ITEMS MainMain MainFrame Runtime Scheduler Replay Network Socket UI_ "game/LOAD" "game/MAIN/MainMain" Platform_GetMempack ArenaReset_On)
        string(FIND "${${unit}}" "${forbidden}" found)
        if(NOT found EQUAL -1)
            message(FATAL_ERROR "topology lease authority: forbidden ${unit} token ${forbidden}")
        endif()
    endforeach()
endforeach()
file(READ "${CMAKE_CURRENT_LIST_DIR}/../docs/TOPOLOGY_LEASE_AUTHORITY.md" contract)
foreach(required IN ITEMS "full load" "hub swap" "checkpoint restore" "mempack arena reset" "inactive hub preload" "NavHeader.last")
    string(FIND "${contract}" "${required}" present)
    if(present EQUAL -1)
        message(FATAL_ERROR "topology lease authority: missing future call-site contract ${required}")
    endif()
endforeach()
