#include "common.h"
#include "MAIN/MainCanonicalDrivers.h"
#include "functions.h"
#include <stdio.h>
struct sData sdata_static;
#define C(x) do{if(!(x)){fprintf(stderr,"fail %d\n",__LINE__);return 1;}}while(0)
#define DRIVER_STUB(name) static volatile int name##_called; void name(struct Thread*t,struct Driver*d){(void)t;(void)d;name##_called++;}
DRIVER_STUB(VehPhysProc_Driving_Init) DRIVER_STUB(VehStuckProc_RevEngine_Init) DRIVER_STUB(VehPhysProc_FreezeEndEvent_Init) DRIVER_STUB(VehStuckProc_Warp_Init) DRIVER_STUB(VehStuckProc_RIP_Init) DRIVER_STUB(VehStuckProc_Tumble_Init) DRIVER_STUB(VehStuckProc_PlantEaten_Init) DRIVER_STUB(VehPhysProc_SpinFirst_Init) DRIVER_STUB(VehPhysProc_PowerSlide_InitSetUpdate) DRIVER_STUB(VehPhysProc_SpinFirst_InitSetUpdate)
DRIVER_STUB(VehPhysProc_Driving_Update) DRIVER_STUB(VehPhysProc_Driving_PhysLinear) DRIVER_STUB(VehPhysProc_Driving_Audio) DRIVER_STUB(VehPhysGeneral_PhysAngular) DRIVER_STUB(VehPhysForce_OnApplyForces) DRIVER_STUB(COLL_MOVED_PlayerSearch) DRIVER_STUB(VehPhysForce_CollideDrivers) DRIVER_STUB(COLL_FIXED_PlayerSearch) DRIVER_STUB(VehPhysGeneral_JumpAndFriction) DRIVER_STUB(VehPhysForce_TranslateMatrix) DRIVER_STUB(VehFrameProc_Driving) DRIVER_STUB(VehEmitter_DriverMain)
DRIVER_STUB(VehPhysProc_FreezeEndEvent_PhysLinear) DRIVER_STUB(VehPhysProc_FreezeVShift_Update) DRIVER_STUB(VehPhysProc_FreezeVShift_ReverseOneFrame) DRIVER_STUB(VehPhysProc_PowerSlide_PhysLinear) DRIVER_STUB(VehPhysProc_PowerSlide_Update) DRIVER_STUB(VehPhysProc_PowerSlide_PhysAngular) DRIVER_STUB(VehPhysProc_SlamWall_Update) DRIVER_STUB(VehPhysProc_SlamWall_PhysLinear) DRIVER_STUB(VehPhysProc_SlamWall_PhysAngular) DRIVER_STUB(VehPhysProc_SlamWall_Animate) DRIVER_STUB(VehPhysProc_SpinFirst_PhysLinear) DRIVER_STUB(VehPhysProc_SpinFirst_PhysAngular) DRIVER_STUB(VehFrameProc_Spinning) DRIVER_STUB(VehPhysProc_SpinFirst_Update) DRIVER_STUB(VehPhysProc_SpinLast_Update) DRIVER_STUB(VehPhysProc_SpinLast_PhysLinear) DRIVER_STUB(VehPhysProc_SpinLast_PhysAngular) DRIVER_STUB(VehFrameProc_LastSpin) DRIVER_STUB(VehPhysProc_SpinStop_Update) DRIVER_STUB(VehPhysProc_SpinStop_PhysLinear) DRIVER_STUB(VehPhysProc_SpinStop_PhysAngular) DRIVER_STUB(VehPhysProc_SpinStop_Animate)
DRIVER_STUB(VehStuckProc_MaskGrab_Update) DRIVER_STUB(VehStuckProc_MaskGrab_PhysLinear) DRIVER_STUB(VehStuckProc_MaskGrab_Animate) DRIVER_STUB(VehStuckProc_PlantEaten_Update) DRIVER_STUB(VehStuckProc_PlantEaten_PhysLinear) DRIVER_STUB(VehStuckProc_PlantEaten_Animate) DRIVER_STUB(VehStuckProc_RevEngine_Update) DRIVER_STUB(VehStuckProc_RevEngine_PhysLinear) DRIVER_STUB(VehStuckProc_RevEngine_Animate) DRIVER_STUB(VehStuckProc_Tumble_Update) DRIVER_STUB(VehStuckProc_Tumble_PhysLinear) DRIVER_STUB(VehStuckProc_Tumble_PhysAngular) DRIVER_STUB(VehStuckProc_Tumble_Animate) DRIVER_STUB(VehStuckProc_Warp_PhysAngular)
static volatile int birth_called,drive_called,rev_called; void VehBirth_NullThread(struct Thread*t){(void)t;birth_called++;} void BOTS_ThTick_Drive(struct Thread*t){(void)t;drive_called++;} void BOTS_ThTick_RevEngine(struct Thread*t){(void)t;rev_called++;}
static void UnknownDriver(struct Thread*t,struct Driver*d){(void)t;(void)d;} static void UnknownThread(struct Thread*t){(void)t;}
#include "../game/MAIN/MainCanonicalDrivers.c"
static int ProjectPreludeTest(void){struct NativeCanonicalDriversRosterInput in;struct NativeCanonicalDriversRosterCandidate out,before;DriverFunc tables[8][13]={{0}};void(*threads[8])(struct Thread*)={0};memset(&in,0,sizeof(in));memset(in.raceOrder,0xff,sizeof(in.raceOrder));memset(in.winnerDriverIDs,0xff,sizeof(in.winnerDriverIDs));memset(in.ranks,0xff,sizeof(in.ranks));memset(in.navOrder,0xff,sizeof(in.navOrder));in.slots[3].present=1;in.slots[3].driverID=3;in.slots[3].kind=NATIVE_CANONICAL_DRIVER_KIND_HUMAN;in.playerCount=1;in.raceOrderCount=1;in.raceOrder[0]=3;in.ranks[0]=7;tables[3][1]=VehPhysProc_Driving_Update;tables[3][2]=VehPhysProc_Driving_PhysLinear;tables[3][3]=VehPhysProc_Driving_Audio;tables[3][4]=VehPhysGeneral_PhysAngular;tables[3][5]=VehPhysForce_OnApplyForces;tables[3][6]=COLL_MOVED_PlayerSearch;tables[3][7]=VehPhysForce_CollideDrivers;tables[3][8]=COLL_FIXED_PlayerSearch;tables[3][9]=VehPhysGeneral_JumpAndFriction;tables[3][10]=VehPhysForce_TranslateMatrix;tables[3][11]=VehFrameProc_Driving;tables[3][12]=VehEmitter_DriverMain;threads[3]=VehBirth_NullThread;if(!MainCanonicalDrivers_ProjectPrelude(&in,tables,threads,&out)||out.behaviorID[3]!=1||out.threadBehaviorID[3]!=1)return 0;before=out;tables[3][7]=UnknownDriver;if(MainCanonicalDrivers_ProjectPrelude(&in,tables,threads,&out)||memcmp(&out,&before,sizeof(out))!=0)return 0;return 1;}
int main(void){DriverFunc driving[13]={NULL,VehPhysProc_Driving_Update,VehPhysProc_Driving_PhysLinear,VehPhysProc_Driving_Audio,VehPhysGeneral_PhysAngular,VehPhysForce_OnApplyForces,COLL_MOVED_PlayerSearch,VehPhysForce_CollideDrivers,COLL_FIXED_PlayerSearch,VehPhysGeneral_JumpAndFriction,VehPhysForce_TranslateMatrix,VehFrameProc_Driving,VehEmitter_DriverMain};uint8_t id=0x5a,keep=id;int binding=MainCanonicalDrivers_ValidateProductionBinding();C(binding==1);C(MainCanonicalDrivers_ProductionRegistry()!=NULL);C(MainCanonicalDrivers_ResolveBehavior(driving,&id)&&id==1);driving[7]=UnknownDriver;C(!MainCanonicalDrivers_ResolveBehavior(driving,&id)&&id==1);C(MainCanonicalDrivers_ResolveThread(NULL,&id)&&id==0);C(MainCanonicalDrivers_ResolveThread(VehBirth_NullThread,&id)&&id==1);C(MainCanonicalDrivers_ResolveThread(BOTS_ThTick_Drive,&id)&&id==2);C(MainCanonicalDrivers_ResolveThread(BOTS_ThTick_RevEngine,&id)&&id==3);id=keep;C(!MainCanonicalDrivers_ResolveThread(UnknownThread,&id)&&id==keep);C(ProjectPreludeTest());puts("main_canonical_drivers_binding_test: passed");return 0;}
