file(READ "${CMAKE_CURRENT_LIST_DIR}/../CMakeLists.txt" cmake)
string(REGEX MATCH "target_link_libraries\\([ \t\r\n]*ctr_native_bot_tick_evidence([^)]+)\\)" call "${cmake}")
if(NOT call)
    message(FATAL_ERROR "bot tick evidence: missing direct link declaration")
endif()
set(deps "${CMAKE_MATCH_1}")
string(REGEX REPLACE "[ \t\r\n]+" ";" deps "${deps}")
list(REMOVE_ITEM deps "" PUBLIC PRIVATE INTERFACE)
set(allowed ctr_native_arcade_bot_setup ctr_native_canonical_drivers_detailed ctr_native_match_config ctr_native_deterministic_rng)
foreach(dep IN LISTS deps)
    list(FIND allowed "${dep}" i)
    if(i EQUAL -1)
        message(FATAL_ERROR "bot tick evidence: forbidden direct dependency ${dep}")
    endif()
endforeach()
list(LENGTH deps dependency_count)
if(NOT dependency_count EQUAL 4)
    message(FATAL_ERROR "bot tick evidence: direct dependency allowlist changed")
endif()
foreach(forbidden ctr_native ctr_native_canonical_runtime ctr_native_replay_scheduler_v4 ctr_native_replay_v4 ctr_native_replay_v4_file)
    string(REGEX MATCH "target_link_libraries\\([ \t\r\n]*${forbidden}[^)]*ctr_native_bot_tick_evidence" bad "${cmake}")
    if(bad)
        message(FATAL_ERROR "bot tick evidence: forbidden consumer ${forbidden}")
    endif()
endforeach()
file(READ "${CMAKE_CURRENT_LIST_DIR}/../game/MAIN/MainArcadeBotTickEvidence.c" source)
foreach(forbidden_include "MainRace" "MainGame" "MainCanonicalRuntime" "native_replay" "native_network" "native_socket")
    string(FIND "${source}" "${forbidden_include}" forbidden_offset)
    if(NOT forbidden_offset EQUAL -1)
        message(FATAL_ERROR "bot tick evidence: forbidden source reference ${forbidden_include}")
    endif()
endforeach()
