set(root "${CMAKE_CURRENT_LIST_DIR}/..")
file(READ "${root}/CMakeLists.txt" cmake)
file(READ "${root}/game/MAIN/MainCanonicalTopologyLeaseRuntime.c" runtime)
file(READ "${root}/game/game_unity.h" unity_source)
file(READ "${root}/game/MAIN/MainMain.c" main_source)
file(READ "${root}/game/LOAD/LOAD_Level.c" level_source)
file(READ "${root}/game/LOAD/LOAD_Hub.c" hub_source)
file(READ "${root}/platform/native_checkpoint.c" checkpoint_source)

string(FIND "${cmake}" "add_executable(ctr_native main.c)" native_executable_start)
if(native_executable_start EQUAL -1)
    message(FATAL_ERROR "main_canonical_topology_lease_runtime_isolation: missing exact ctr_native executable declaration")
endif()
string(SUBSTRING "${cmake}" ${native_executable_start} -1 native_executable_tail)
string(FIND "${native_executable_tail}" "target_link_libraries(ctr_native " native_link_start)
if(native_link_start EQUAL -1)
    message(FATAL_ERROR "main_canonical_topology_lease_runtime_isolation: missing exact ctr_native link declaration")
endif()
string(SUBSTRING "${native_executable_tail}" ${native_link_start} -1 native_link_tail)
string(FIND "${native_link_tail}" ")" native_link_end)
if(native_link_end EQUAL -1)
    message(FATAL_ERROR "main_canonical_topology_lease_runtime_isolation: unterminated exact ctr_native link declaration")
endif()
string(SUBSTRING "${native_link_tail}" 0 ${native_link_end} native_link_block)
string(FIND "${native_link_block}" "main_canonical_topology_lifecycle_events" native_link_hit)
if(native_link_hit EQUAL -1)
    message(FATAL_ERROR "main_canonical_topology_lease_runtime_isolation: ctr_native must link the value-only recorder")
endif()

foreach(forbidden IN ITEMS Acquire Capture ActivatePostInit Adapter CanonicalState Replay Scheduler Network Socket Protocol Serialize Publish)
    string(FIND "${runtime}" "${forbidden}" hit)
    if(NOT hit EQUAL -1)
        message(FATAL_ERROR "main_canonical_topology_lease_runtime_isolation: runtime must not contain ${forbidden}")
    endif()
endforeach()

function(assert_order source)
    set(last -1)
    foreach(term IN LISTS ARGN)
        string(FIND "${source}" "${term}" position)
        if(position EQUAL -1 OR position LESS last)
            message(FATAL_ERROR "main_canonical_topology_lease_runtime_isolation: required order missing for ${term}")
        endif()
        set(last ${position})
    endforeach()
endfunction()

assert_order("${unity_source}" "MAIN/MainCanonicalTopologyLeaseAuthority.c" "MAIN/MainCanonicalTopologyLeaseRuntime.c")
assert_order("${main_source}"
	"MainCanonicalTopologyLeaseRuntime_BeforeGameTrackerZero" "memset(gGT, 0, sizeof(*gGT))" "MainCanonicalTopologyLeaseRuntime_ResetAfterGameTrackerZero"
    "MainCanonicalTopologyLeaseRuntime_BeforeArenaReset" "MEMPACK_Init(MEMPACK_SIZE)")
assert_order("${level_source}"
    "void LOAD_LevelFile(int levelID)" "MainCanonicalTopologyLeaseRuntime_BeforeFullLoad")
string(FIND "${level_source}" "void LOAD_LevelFile(int levelID)" level_start)
string(SUBSTRING "${level_source}" ${level_start} -1 level_body)
assert_order("${level_body}" "MainCanonicalTopologyLeaseRuntime_BeforeFullLoad" "sdata->modelMaskHints3D = 0")
assert_order("${hub_source}"
    "void LOAD_Hub_SwapNow()" "MainCanonicalTopologyLeaseRuntime_BeforeHubSwap" "LevInstDef_RePack")
assert_order("${checkpoint_source}"
    "NativeCheckpoint_ValidateHeader(header, srcSize)" "NativeTopologyLeaseRuntime_BeforeCheckpointRestore" "OVR233_ResetRuntimeState")
string(FIND "${main_source}" "sdata->mainGameState = 3" boot_state_start)
string(SUBSTRING "${main_source}" ${boot_state_start} -1 boot_state_body)
assert_order("${boot_state_body}" "MainCanonicalTopologyLeaseRuntime_BeforeFullLoad" "sdata->Loading.stage = LOAD_TEN_STAGES_0")
string(REGEX MATCH "void MainCanonicalTopologyLeaseRuntime_BeforeGameTrackerZero\\(void\\)[^{]*\\{[^}]*RetireAtMutation\\(MAIN_CANONICAL_TOPOLOGY_LEASE_RETIRE_ARENA_RESET,[ \t\r\n]*MAIN_CANONICAL_TOPOLOGY_LIFECYCLE_REASON_GAME_TRACKER_ZERO" tracker_zero_transition "${runtime}")
if(NOT tracker_zero_transition)
    message(FATAL_ERROR "main_canonical_topology_lease_runtime_isolation: game-tracker clear must use distinct trace evidence")
endif()

string(FIND "${hub_source}" "void LOAD_Hub_ReadFile" preload_start)
string(FIND "${hub_source}" "void LOAD_Hub_SwapNow" swap_start)
string(SUBSTRING "${hub_source}" ${preload_start} ${swap_start} preload_body)
string(FIND "${preload_body}" "MainCanonicalTopologyLeaseRuntime_" preload_hook)
if(NOT preload_hook EQUAL -1)
    message(FATAL_ERROR "main_canonical_topology_lease_runtime_isolation: inactive hub preload must not retire the owner")
endif()

foreach(forbidden IN ITEMS NATIVE_CHECKPOINT_REGION_TOPOLOGY MainCanonicalTopologyLeaseRuntimeEvidence)
    string(FIND "${checkpoint_source}" "${forbidden}" hit)
    if(NOT hit EQUAL -1)
        message(FATAL_ERROR "main_canonical_topology_lease_runtime_isolation: checkpoint must not serialize ${forbidden}")
    endif()
endforeach()
