file(READ "${CMAKE_CURRENT_LIST_DIR}/../CMakeLists.txt" cmake)
set(target main_canonical_topology_lease_adapter)
string(FIND "${cmake}" "add_library(${target} STATIC" declared)
if(declared EQUAL -1)
    message(FATAL_ERROR "topology lease adapter: missing isolated leaf target")
endif()
string(REGEX MATCH "target_link_libraries\\(${target}[ \\t\\r\\n]+([^)]*)\\)" links "${cmake}")
if(NOT links)
    message(FATAL_ERROR "topology lease adapter: missing direct dependency declaration")
endif()
set(deps "${CMAKE_MATCH_1}")
string(REGEX MATCHALL "[A-Za-z0-9_]+" deps "${deps}")
list(REMOVE_ITEM deps "" PUBLIC PRIVATE INTERFACE)
set(allowed main_canonical_topology_lease_authority ctr_native_canonical_topology_facts)
if(NOT "${deps}" STREQUAL "${allowed}")
    message(FATAL_ERROR "topology lease adapter: unexpected direct dependencies: ${deps}")
endif()
foreach(consumer IN ITEMS ctr_native ctr_native_topology_asset_census_tool ctr_native_canonical_runtime ctr_native_replay_scheduler_seam ctr_native_replay_scheduler_v3 ctr_native_replay_scheduler_v4 ctr_native_replay_v2 ctr_native_replay_v3 ctr_native_replay_v4 ctr_native_replay_v4_file ctr_native_canonical_state_v3 ctr_native_canonical_state_v4 ctr_native_canonical_projector ctr_native_canonical_projector_v4 ctr_native_canonical_exact_domains_v4 ctr_native_arcade_setup_v4 ctr_native_canonical_topology main_canonical_topology_lease_authority ctr_native_canonical_topology_facts)
    string(REGEX MATCH "target_link_libraries\\(${consumer}[^)]*${target}" hit "${cmake}")
    if(hit)
        message(FATAL_ERROR "topology lease adapter: ${consumer} must not consume dormant leaf")
    endif()
endforeach()
file(READ "${CMAKE_CURRENT_LIST_DIR}/../game/MAIN/MainCanonicalTopologyLeaseAdapter.h" header)
file(READ "${CMAKE_CURRENT_LIST_DIR}/../game/MAIN/MainCanonicalTopologyLeaseAdapter.c" source)
file(READ "${CMAKE_CURRENT_LIST_DIR}/../game/MAIN/MainCanonicalTopologyFacts.h" facts_header)
file(READ "${CMAKE_CURRENT_LIST_DIR}/../game/MAIN/MainCanonicalTopologyFacts.c" facts_source)
string(REGEX MATCHALL "#[ \t]*include[ \t]+\"[^\"]+\"" header_includes "${header}")
set(allowed_header_includes "MAIN/MainCanonicalTopologyLeaseAuthority.h" "MAIN/MainCanonicalTopologyFacts.h")
foreach(include_line IN LISTS header_includes)
    string(REGEX REPLACE ".*\"([^\"]+)\".*" "\\1" include_path "${include_line}")
    list(FIND allowed_header_includes "${include_path}" include_index)
    if(include_index EQUAL -1)
        message(FATAL_ERROR "topology lease adapter: forbidden public-header include ${include_path}")
    endif()
endforeach()
foreach(facts_unit IN ITEMS facts_header facts_source)
    string(FIND "${${facts_unit}}" "MainCanonicalTopologyLeaseAdapter" facts_hit)
    if(NOT facts_hit EQUAL -1)
        message(FATAL_ERROR "topology lease adapter: facts must not reference adapter")
    endif()
endforeach()
foreach(required IN ITEMS MainCanonicalTopologyLeaseAdapterGuardFn BeforeNativeRead MainCanonicalTopologyLease_Acquire MainCanonicalTopologyLease_ObservePostInit MainCanonicalTopologyLease_Validate MainCanonicalTopologyFactReader_ToV1 NativeTopologyResidencyV1_Capture NativeTopologyResidencyV1_Validate)
    string(FIND "${source}" "${required}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "topology lease adapter: missing required guard ${required}")
    endif()
endforeach()
foreach(unit IN ITEMS header source)
    foreach(forbidden IN ITEMS MainMain MainFrame Runtime Scheduler Replay Network Socket UI_ "game/LOAD" "game/MAIN/MainMain" Platform_GetMempack ArenaReset_On "malloc(" "calloc(" "realloc(" "free(")
        string(FIND "${${unit}}" "${forbidden}" found)
        if(NOT found EQUAL -1)
            message(FATAL_ERROR "topology lease adapter: forbidden ${unit} token ${forbidden}")
        endif()
    endforeach()
endforeach()
