file(READ "${CMAKE_CURRENT_LIST_DIR}/../CMakeLists.txt" cmake)
set(target ctr_native_virtual_datagram)
string(FIND "${cmake}" "add_library(${target} STATIC platform/native_virtual_datagram.c)" declaration)
if(declaration EQUAL -1)
    message(FATAL_ERROR "virtual datagram: missing standalone target")
endif()
string(REGEX MATCH "target_link_libraries\\([ \\t\\r\\n]*${target}[^)]*\\)" links "${cmake}")
if(links)
    message(FATAL_ERROR "virtual datagram: target must not link dependencies")
endif()
string(REGEX MATCHALL "target_link_libraries\\([^)]*${target}[^)]*\\)" consumers "${cmake}")
list(LENGTH consumers consumer_count)
if(NOT consumer_count EQUAL 1)
    message(FATAL_ERROR "virtual datagram: exactly one fixture consumer is required")
endif()
list(GET consumers 0 consumer)
string(FIND "${consumer}" "target_link_libraries(native_virtual_datagram_test" fixture)
if(fixture EQUAL -1)
    message(FATAL_ERROR "virtual datagram: only its dedicated fixture may consume harness")
endif()
file(READ "${CMAKE_CURRENT_LIST_DIR}/../include/platform/native_virtual_datagram.h" header)
file(READ "${CMAKE_CURRENT_LIST_DIR}/../platform/native_virtual_datagram.c" source)
foreach(forbidden IN ITEMS
    winsock WinSock WSA socket Socket UDP udp SDL
    "main.c" MainMain "native_input" "native_replay"
    "game/" "Game_" protocol Protocol packet Packet admission Admission)
    string(FIND "${header}" "${forbidden}" at)
    if(NOT at EQUAL -1)
        message(FATAL_ERROR "virtual datagram: forbidden header token ${forbidden}")
    endif()
    string(FIND "${source}" "${forbidden}" at)
    if(NOT at EQUAL -1)
        message(FATAL_ERROR "virtual datagram: forbidden source token ${forbidden}")
    endif()
endforeach()
