file(READ "${CMAKE_CURRENT_LIST_DIR}/../CMakeLists.txt" cmake)
set(target ctr_native_topology_asset_census)
string(REGEX MATCH "target_link_libraries\\([ \\t\\r\\n]*${target}[^)]*\\)" links "${cmake}")
foreach(forbidden IN ITEMS ctr_native_canonical_runtime ctr_native_replay_scheduler_v4 ctr_native_replay_v4 ctr_native_replay_v4_file ctr_native_canonical_projector ctr_native_arcade_setup_v4)
    string(FIND "${links}" "${forbidden}" found)
    if(NOT found EQUAL -1)
        message(FATAL_ERROR "topology asset census must not link ${forbidden}")
    endif()
endforeach()
foreach(forbidden IN ITEMS DuckStation OnlineCTR socket send recv MainMain UI)
    string(FIND "${cmake}" "${target} STATIC ${forbidden}" bad)
endforeach()
file(READ "${CMAKE_CURRENT_LIST_DIR}/../platform/native_topology_asset_census.c" source)
foreach(forbidden IN ITEMS native_disc_image emulator DuckStation OnlineCTR socket recv send)
    string(FIND "${source}" "${forbidden}" found)
    if(NOT found EQUAL -1)
        message(FATAL_ERROR "topology asset census source forbidden token ${forbidden}")
    endif()
endforeach()
