file(STRINGS "${CMAKE_CURRENT_LIST_DIR}/../CMakeLists.txt" cmake_lines)
set(target ctr_native_topology_asset_census)
set(declaration "")
set(links "")
set(consumers "")

function(is_target_link_call line name output)
    if("${line}" MATCHES "^target_link_libraries\\(${name} ")
        set(${output} 1 PARENT_SCOPE)
    else()
        set(${output} 0 PARENT_SCOPE)
    endif()
endfunction()

function(has_target_argument line name output)
    string(FIND "${line}" " ${name}" argument_offset)
    if(argument_offset EQUAL -1)
        set(${output} 0 PARENT_SCOPE)
    else()
        set(${output} 1 PARENT_SCOPE)
    endif()
endfunction()

# Inspect the actual one-call-per-line target declaration/link convention in
# this CMake file.  The audit intentionally does not invent a literal that
# joins add_library() and target_link_libraries(): they are separate calls.
foreach(raw_line IN LISTS cmake_lines)
    string(STRIP "${raw_line}" line)
    if(line MATCHES "^add_library\\(${target} STATIC ")
        set(declaration "${line}")
    endif()
    is_target_link_call("${line}" "${target}" is_direct_link)
    if(is_direct_link)
        set(links "${line}")
    endif()
    # A dependency token must be preceded by a CMake argument separator,
    # which prevents name-substring matches such as native_*_census_test.
    has_target_argument("${line}" "${target}" has_target_argument)
    if(has_target_argument AND line MATCHES "^target_link_libraries\\(")
        list(APPEND consumers "${line}")
    endif()
endforeach()

if(declaration STREQUAL "")
    message(FATAL_ERROR "topology asset census target declaration is missing")
endif()
if(links STREQUAL "")
    message(FATAL_ERROR "topology asset census direct dependency block is missing")
endif()
foreach(forbidden IN ITEMS ctr_native_canonical_runtime ctr_native_replay_scheduler_v4 ctr_native_replay_v4 ctr_native_replay_v4_file ctr_native_canonical_projector ctr_native_arcade_setup_v4)
    string(FIND "${links}" "${forbidden}" found)
    if(NOT found EQUAL -1)
        message(FATAL_ERROR "topology asset census must not link ${forbidden}")
    endif()
endforeach()

# Broad integration tokens are checked only in this target's concrete scope;
# they are valid elsewhere in the top-level project.
set(target_scope "${declaration}\n${links}")
foreach(forbidden IN ITEMS DuckStation OnlineCTR socket send recv MainMain UI)
    string(FIND "${target_scope}" "${forbidden}" bad)
    if(NOT bad EQUAL -1)
        message(FATAL_ERROR "topology asset census CMake forbidden token ${forbidden}")
    endif()
endforeach()

# The census library may be consumed only by its offline CLI and unit test.
foreach(consumer_line IN LISTS consumers)
    string(REGEX MATCH "^target_link_libraries\\(([A-Za-z0-9_]+) " consumer_header "${consumer_line}")
    set(consumer "${CMAKE_MATCH_1}")
    if(consumer STREQUAL "${target}")
        string(REGEX REPLACE "^target_link_libraries\\(${target} (PUBLIC|PRIVATE|INTERFACE) " "" own_dependencies "${consumer_line}")
        string(FIND "${own_dependencies}" "${target}" self_link)
        if(NOT self_link EQUAL -1)
            message(FATAL_ERROR "topology asset census must not link itself")
        endif()
    elseif(NOT consumer STREQUAL "ctr_native_topology_asset_census_tool" AND NOT consumer STREQUAL "native_topology_asset_census_test")
        message(FATAL_ERROR "topology asset census has forbidden consumer ${consumer}")
    endif()
endforeach()

# Self-contract fixtures prove direct-dependency and consumer detection are
# live, so a future edit cannot silently reduce this audit to a no-op.
set(forbidden_link_fixture "target_link_libraries(${target} PRIVATE ctr_native_replay_v4)")
is_target_link_call("${forbidden_link_fixture}" "${target}" fixture_direct_link)
string(FIND "${forbidden_link_fixture}" "ctr_native_replay_v4" fixture_forbidden)
if(NOT fixture_direct_link OR fixture_forbidden EQUAL -1)
    message(FATAL_ERROR "topology asset census direct dependency fixture was not detected")
endif()
set(forbidden_consumer_fixture "target_link_libraries(ctr_native_canonical_runtime PRIVATE ${target})")
has_target_argument("${forbidden_consumer_fixture}" "${target}" fixture_consumer)
if(NOT fixture_consumer)
    message(FATAL_ERROR "topology asset census consumer fixture was not detected")
endif()

file(READ "${CMAKE_CURRENT_LIST_DIR}/../platform/native_topology_asset_census.c" source)
foreach(forbidden IN ITEMS native_disc_image emulator DuckStation OnlineCTR socket recv send)
    string(FIND "${source}" "${forbidden}" found)
    if(NOT found EQUAL -1)
        message(FATAL_ERROR "topology asset census source forbidden token ${forbidden}")
    endif()
endforeach()
