#include "platform/native_replay_scheduler_v4.h"
#include <stdio.h>
#include <string.h>
#if defined(_WIN32)
#include <windows.h>
#define PATH_BYTES MAX_PATH
#endif
#define CHECK(x) do { if(!(x)){fprintf(stderr,"%d: %s\n",__LINE__,#x);return 1;} }while(0)
static int Path(char p[PATH_BYTES]) { char d[MAX_PATH];DWORD n=GetTempPathA(sizeof(d),d);return n>0&&n<sizeof(d)&&GetTempFileNameA(d,"s4",0,p)!=0&&remove(p)==0; }
static int Setup(struct NativeReplaySchedulerV4Request *r) { uint8_t st[NATIVE_CANONICAL_DRIVERS_NORMATIVE_BYTES]={0};memset(r,0,sizeof(*r));NativeMatchConfigV1_InitArcadeTwoCab(&r->config);for(uint32_t i=0;i<32;i++)r->identity.build[i]=(uint8_t)(i+1),r->identity.content[i]=(uint8_t)(0x80+i);r->config.trackID=1;r->config.gameMode1=2;r->config.gameMode2=3;r->config.rules=4;r->config.lapCount=3;r->config.tickRateNumerator=30;r->config.tickRateDenominator=1;r->config.masterSeed=5;memcpy(r->config.buildIdentity,r->identity.build,32);memcpy(r->config.contentIdentity,r->identity.content,32);for(uint32_t i=0;i<6;i++)r->config.slots[i].characterID=(uint8_t)i,r->config.slots[i].difficulty=2;for(uint32_t i=0;i<32;i++)r->config.botRulesDigest[i]=(uint8_t)(0x20+i);st[64]=1;return NativeMatchConfigV1_Digest(&r->config,r->configDigest); }
static int Canon(const struct NativeReplaySchedulerV4Request *r,struct NativeCanonicalStateV4 *c) { uint8_t st[NATIVE_CANONICAL_DRIVERS_NORMATIVE_BYTES]={0};NativeCanonicalStateV4_Init(c);c->identity=r->identity;c->frameNumber=r->replayFrame;memcpy(c->configDigest,r->configDigest,32);c->input.pads[0].connected=1;if(!NativeDeterministicRngBankV1_Init(&c->deterministicRng,r->config.masterSeed,r->config.rngDerivationVersion))return 0;st[64]=1;return NativeCanonicalDriversV1_FromNormativeStream(&c->drivers,1,st,sizeof(st))&&NativeCanonicalStateV4_ComputeDigests(c); }
static int Frame(struct NativeReplaySchedulerV4 *s,struct NativeReplaySchedulerV4Request *r) { struct NativeReplayV2FrameObservation b={0},e={0};struct NativeReplayV2Pad p[4]={0};struct NativeCanonicalStateV4 c;uint16_t v=2;uint32_t elapsed=0;int ok;b.frameCounter=(int32_t)r->replayFrame;e.elapsedTimeMS=32+r->replayFrame;p[0].connected=1;CHECK(NativeReplaySchedulerV4_BeginFrame(s,r,&b,p));CHECK(NativeReplaySchedulerV4_ConsumeVSync(s,&v));CHECK(NativeReplaySchedulerV4_ConsumeElapsed(s,&elapsed));CHECK(Canon(r,&c));CHECK(NativeReplaySchedulerV4_SubmitCanonical(s,&c));if(s->mode==NATIVE_REPLAY_SCHEDULER_V4_RECORD){s->pending.end=e;CHECK(NativeReplayV4Frame_Validate(&s->record.header,&s->pending));}ok=NativeReplaySchedulerV4_EndFrame(s,&e);if(!ok)fprintf(stderr,"end mode=%d failed=%d next=%u frame=%u elapsed=%d\n",s->mode,s->record.failed,s->record.nextFrame,r->replayFrame,s->elapsedTaken);CHECK(ok);return 0; }
int main(void) { char p[PATH_BYTES];struct NativeReplaySchedulerV4Request r,bad;struct NativeReplaySchedulerV4 s;CHECK(Setup(&r));CHECK(Path(p));NativeReplaySchedulerV4_Init(&s);CHECK(NativeReplaySchedulerV4_OpenRecord(&s,p,&r.identity,&r.config));CHECK(Frame(&s,&r)==0);r.replayFrame++;CHECK(Frame(&s,&r)==0);CHECK(NativeReplaySchedulerV4_Finalize(&s));NativeReplaySchedulerV4_Close(&s);NativeReplaySchedulerV4_Init(&s);r.replayFrame=0;CHECK(NativeReplaySchedulerV4_OpenPlayback(&s,p,&r.identity,&r.config));CHECK(Frame(&s,&r)==0);r.replayFrame++;CHECK(Frame(&s,&r)==0);r.replayFrame++;{struct NativeReplayV2FrameObservation o={0};struct NativeReplayV2Pad pads[4]={0};CHECK(!NativeReplaySchedulerV4_BeginFrame(&s,&r,&o,pads));CHECK(s.mode==NATIVE_REPLAY_SCHEDULER_V4_POISON);}NativeReplaySchedulerV4_Close(&s);/* request/digest and reentry are poison */NativeReplaySchedulerV4_Init(&s);CHECK(NativeReplaySchedulerV4_OpenRecord(&s,p,&r.identity,&r.config));bad=r;bad.configDigest[0]^=1;{struct NativeReplayV2FrameObservation o={0};struct NativeReplayV2Pad pads[4]={0};CHECK(!NativeReplaySchedulerV4_BeginFrame(&s,&bad,&o,pads));CHECK(s.mode==NATIVE_REPLAY_SCHEDULER_V4_POISON);}NativeReplaySchedulerV4_Close(&s);CHECK(remove(p)==0);puts("native_replay_scheduler_v4_test: passed");return 0; }
