#include "platform/native_replay_scheduler_v4.h"
#include <stdio.h>
#include <string.h>
#if defined(_WIN32)
#include <windows.h>
#define PATH_BYTES MAX_PATH
#else
#include <unistd.h>
#define PATH_BYTES 512
#endif
#define CHECK(x) do{if(!(x)){fprintf(stderr,"%d: %s\n",__LINE__,#x);return 1;}}while(0)
static int Path(char p[PATH_BYTES]){
#if defined(_WIN32)
	char d[MAX_PATH];DWORD n=GetTempPathA(sizeof(d),d);return n>0&&n<sizeof(d)&&GetTempFileNameA(d,"s4",0,p)!=0&&remove(p)==0;
#else
	char t[]="/tmp/ctr-s4-XXXXXX";int x=mkstemp(t);if(x<0||close(x)!=0)return 0;if(unlink(t)!=0)return 0;memcpy(p,t,sizeof(t));return 1;
#endif
}
static int Setup(struct NativeReplaySchedulerV4Request *r){memset(r,0,sizeof(*r));NativeMatchConfigV1_InitArcadeTwoCab(&r->config);for(uint32_t i=0;i<32;i++)r->identity.build[i]=(uint8_t)(i+1),r->identity.content[i]=(uint8_t)(0x80+i);r->config.trackID=1;r->config.gameMode1=2;r->config.gameMode2=3;r->config.rules=4;r->config.lapCount=3;r->config.tickRateNumerator=30;r->config.tickRateDenominator=1;r->config.masterSeed=5;memcpy(r->config.buildIdentity,r->identity.build,32);memcpy(r->config.contentIdentity,r->identity.content,32);for(uint32_t i=0;i<6;i++)r->config.slots[i].characterID=(uint8_t)i,r->config.slots[i].difficulty=2;for(uint32_t i=0;i<32;i++)r->config.botRulesDigest[i]=(uint8_t)(0x20+i);return NativeMatchConfigV1_Digest(&r->config,r->configDigest);}
static int Canon(const struct NativeReplaySchedulerV4Request *r,const struct NativeReplayV2Pad pads[4],struct NativeCanonicalStateV4 *c){uint8_t st[NATIVE_CANONICAL_DRIVERS_NORMATIVE_BYTES]={0};NativeCanonicalStateV4_Init(c);c->identity=r->identity;c->frameNumber=r->replayFrame;memcpy(c->configDigest,r->configDigest,32);for(uint32_t i=0;i<4;i++){c->input.pads[i].status=pads[i].status;c->input.pads[i].id=pads[i].id;memcpy(c->input.pads[i].buttons,pads[i].buttons,2);memcpy(c->input.pads[i].analog,pads[i].analog,4);c->input.pads[i].connected=pads[i].connected;}if(!NativeDeterministicRngBankV1_Init(&c->deterministicRng,r->config.masterSeed,r->config.rngDerivationVersion))return 0;st[64]=1;return NativeCanonicalDriversV1_FromNormativeStream(&c->drivers,1,st,sizeof(st))&&NativeCanonicalStateV4_ComputeDigests(c);}
static void Inputs(uint32_t n,struct NativeReplayV2FrameObservation *b,struct NativeReplayV2FrameObservation *e,struct NativeReplayV2Pad pads[4]){memset(b,0,sizeof(*b));memset(e,0,sizeof(*e));memset(pads,0,4*sizeof(*pads));b->frameCounter=(int32_t)n;e->elapsedTimeMS=32+(int32_t)n;pads[0].status=1;pads[0].id=2;pads[0].buttons[0]=3;pads[0].analog[1]=4;pads[0].connected=1;}
static int RecordOne(struct NativeReplaySchedulerV4 *s,struct NativeReplaySchedulerV4Request *r){struct NativeReplayV2FrameObservation b,e;struct NativeReplayV2Pad pads[4];struct NativeCanonicalStateV4 c;uint16_t v=2;uint32_t elapsed=0;Inputs(r->replayFrame,&b,&e,pads);CHECK(NativeReplaySchedulerV4_BeginFrame(s,r,&b,pads));CHECK(NativeReplaySchedulerV4_ConsumeVSync(s,&v));CHECK(NativeReplaySchedulerV4_ConsumeElapsed(s,&elapsed));CHECK(Canon(r,pads,&c));CHECK(NativeReplaySchedulerV4_SubmitCanonical(s,&c));CHECK(NativeReplaySchedulerV4_EndFrame(s,&e));return 0;}
static int MakeRecording(const char *p,struct NativeReplaySchedulerV4Request *r){struct NativeReplaySchedulerV4 s;NativeReplaySchedulerV4_Init(&s);CHECK(NativeReplaySchedulerV4_OpenRecord(&s,p,&r->identity,&r->config));CHECK(RecordOne(&s,r)==0);CHECK(NativeReplaySchedulerV4_Finalize(&s));NativeReplaySchedulerV4_Close(&s);return 0;}
/* variant: 1 observation, 2 pad, 3 missing VSync, 4 extra VSync, 5 canonical. */
static int PlaybackMismatch(const char *p,struct NativeReplaySchedulerV4Request *r,int variant){struct NativeReplaySchedulerV4 s;struct NativeReplayV2FrameObservation b,e;struct NativeReplayV2Pad pads[4];struct NativeCanonicalStateV4 c;const struct NativeReplaySchedulerV4MismatchReport *report;uint16_t v=0;uint32_t elapsed=0,next;Inputs(r->replayFrame,&b,&e,pads);if(variant==1)b.frameCounter++;NativeReplaySchedulerV4_Init(&s);CHECK(NativeReplaySchedulerV4_OpenPlayback(&s,p,&r->identity,&r->config));CHECK(NativeReplaySchedulerV4_BeginFrame(&s,r,&b,pads));if(variant!=3){CHECK(NativeReplaySchedulerV4_ConsumeVSync(&s,&v)&&v==2);if(variant==4)CHECK(!NativeReplaySchedulerV4_ConsumeVSync(&s,&v));}CHECK(NativeReplaySchedulerV4_ConsumeElapsed(&s,&elapsed)&&elapsed==(uint32_t)e.elapsedTimeMS);if(variant==2)pads[0].buttons[1]^=1;CHECK(Canon(r,pads,&c));if(variant==5){c.control.frameCounter++;CHECK(NativeCanonicalStateV4_ComputeDigests(&c));}CHECK(NativeReplaySchedulerV4_SubmitCanonical(&s,&c));CHECK(!NativeReplaySchedulerV4_EndFrame(&s,&e));report=NativeReplaySchedulerV4_FirstMismatch(&s);CHECK(report&&report->expectedFrame==r->replayFrame&&report->liveFrame==r->replayFrame);if(variant==1)CHECK(report->mask==NATIVE_REPLAY_SCHEDULER_V4_MISMATCH_OBSERVATION);if(variant==2)CHECK((report->mask&(NATIVE_REPLAY_SCHEDULER_V4_MISMATCH_PAD|NATIVE_REPLAY_SCHEDULER_V4_MISMATCH_CANONICAL_DOMAIN|NATIVE_REPLAY_SCHEDULER_V4_MISMATCH_COMBINED))==(NATIVE_REPLAY_SCHEDULER_V4_MISMATCH_PAD|NATIVE_REPLAY_SCHEDULER_V4_MISMATCH_CANONICAL_DOMAIN|NATIVE_REPLAY_SCHEDULER_V4_MISMATCH_COMBINED)&&report->canonicalDomainMask==(UINT32_C(1)<<2));if(variant==3)CHECK(report->mask==NATIVE_REPLAY_SCHEDULER_V4_MISMATCH_VSYNC&&report->expectedVsyncCount==1&&report->liveVsyncCount==0);if(variant==4)CHECK(report->mask==NATIVE_REPLAY_SCHEDULER_V4_MISMATCH_VSYNC&&report->expectedVsyncCount==1&&report->liveVsyncCount==2);if(variant==5)CHECK((report->mask&(NATIVE_REPLAY_SCHEDULER_V4_MISMATCH_CANONICAL_DOMAIN|NATIVE_REPLAY_SCHEDULER_V4_MISMATCH_COMBINED))==(NATIVE_REPLAY_SCHEDULER_V4_MISMATCH_CANONICAL_DOMAIN|NATIVE_REPLAY_SCHEDULER_V4_MISMATCH_COMBINED)&&report->canonicalDomainMask==(UINT32_C(1)<<0));next=s.playback.nextFrame;CHECK(!NativeReplaySchedulerV4_BeginFrame(&s,r,&b,pads));CHECK(s.mode==NATIVE_REPLAY_SCHEDULER_V4_MISMATCH&&s.playback.nextFrame==next&&NativeReplaySchedulerV4_FirstMismatch(&s)==report);NativeReplaySchedulerV4_Close(&s);return 0;}
static int PoisonSubmission(const char *p,struct NativeReplaySchedulerV4Request *r,int kind){struct NativeReplaySchedulerV4 s;struct NativeReplayV2FrameObservation b,e;struct NativeReplayV2Pad pads[4];struct NativeCanonicalStateV4 c;Inputs(r->replayFrame,&b,&e,pads);NativeReplaySchedulerV4_Init(&s);CHECK(NativeReplaySchedulerV4_OpenRecord(&s,p,&r->identity,&r->config));CHECK(NativeReplaySchedulerV4_BeginFrame(&s,r,&b,pads));CHECK(Canon(r,pads,&c));if(kind==1)c.frameNumber++;else if(kind==2)c.deterministicRng.masterSeed++;else c.combinedDigest++;CHECK(!NativeReplaySchedulerV4_SubmitCanonical(&s,&c));CHECK(s.mode==NATIVE_REPLAY_SCHEDULER_V4_POISON);NativeReplaySchedulerV4_Close(&s);return 0;}
int main(void){char p[PATH_BYTES],q[PATH_BYTES];struct NativeReplaySchedulerV4Request r,bad;struct NativeReplaySchedulerV4 s;struct NativeReplayV2FrameObservation b,e;struct NativeReplayV2Pad pads[4];struct NativeCanonicalStateV4 c;uint16_t v=2;uint32_t elapsed=0;CHECK(Setup(&r));CHECK(Path(p));CHECK(MakeRecording(p,&r)==0);for(int i=1;i<=5;i++)CHECK(PlaybackMismatch(p,&r,i)==0);/* Record verifies sampled pads against the submitted canonical state before disk append. */
Inputs(0,&b,&e,pads);NativeReplaySchedulerV4_Init(&s);CHECK(NativeReplaySchedulerV4_OpenRecord(&s,p,&r.identity,&r.config));CHECK(NativeReplaySchedulerV4_BeginFrame(&s,&r,&b,pads));CHECK(NativeReplaySchedulerV4_ConsumeVSync(&s,&v));CHECK(NativeReplaySchedulerV4_ConsumeElapsed(&s,&elapsed));CHECK(Canon(&r,pads,&c));c.input.pads[0].buttons[0]^=1;CHECK(NativeCanonicalStateV4_ComputeDigests(&c));CHECK(NativeReplaySchedulerV4_SubmitCanonical(&s,&c));CHECK(!NativeReplaySchedulerV4_EndFrame(&s,&e)&&s.mode==NATIVE_REPLAY_SCHEDULER_V4_POISON);NativeReplaySchedulerV4_Close(&s);
/* Public lifecycle and malformed-ingress failures poison without private-state edits. */
NativeReplaySchedulerV4_Init(&s);CHECK(!NativeReplaySchedulerV4_Finalize(NULL));CHECK(NativeReplaySchedulerV4_OpenRecord(&s,p,&r.identity,&r.config));CHECK(!NativeReplaySchedulerV4_BeginFrame(&s,NULL,&b,pads)&&s.mode==NATIVE_REPLAY_SCHEDULER_V4_POISON);NativeReplaySchedulerV4_Close(&s);CHECK(Path(q));Inputs(0,&b,&e,pads);NativeReplaySchedulerV4_Init(&s);CHECK(NativeReplaySchedulerV4_OpenRecord(&s,q,&r.identity,&r.config));CHECK(NativeReplaySchedulerV4_BeginFrame(&s,&r,&b,pads));CHECK(!NativeReplaySchedulerV4_Finalize(&s)&&s.mode==NATIVE_REPLAY_SCHEDULER_V4_POISON);NativeReplaySchedulerV4_Close(&s);CHECK(PoisonSubmission(q,&r,1)==0);CHECK(PoisonSubmission(q,&r,2)==0);CHECK(PoisonSubmission(q,&r,3)==0);bad=r;bad.configDigest[0]^=1;NativeReplaySchedulerV4_Init(&s);CHECK(NativeReplaySchedulerV4_OpenRecord(&s,q,&r.identity,&r.config));CHECK(!NativeReplaySchedulerV4_BeginFrame(&s,&bad,&b,pads)&&s.mode==NATIVE_REPLAY_SCHEDULER_V4_POISON);NativeReplaySchedulerV4_Close(&s);
/* Begin reentry and append/finalize I/O faults are propagated by public calls. */
NativeReplaySchedulerV4_Init(&s);CHECK(NativeReplaySchedulerV4_OpenRecord(&s,q,&r.identity,&r.config));CHECK(NativeReplaySchedulerV4_BeginFrame(&s,&r,&b,pads));CHECK(!NativeReplaySchedulerV4_BeginFrame(&s,&r,&b,pads)&&s.mode==NATIVE_REPLAY_SCHEDULER_V4_POISON);NativeReplaySchedulerV4_Close(&s);NativeReplaySchedulerV4_Init(&s);CHECK(NativeReplaySchedulerV4_OpenRecord(&s,q,&r.identity,&r.config));NativeReplayV4File_TestSetFault(NATIVE_REPLAY_V4_FILE_TEST_FAULT_APPEND);CHECK(RecordOne(&s,&r)!=0&&s.mode==NATIVE_REPLAY_SCHEDULER_V4_POISON);NativeReplaySchedulerV4_Close(&s);NativeReplaySchedulerV4_Init(&s);CHECK(NativeReplaySchedulerV4_OpenRecord(&s,q,&r.identity,&r.config));CHECK(RecordOne(&s,&r)==0);NativeReplayV4File_TestSetFault(NATIVE_REPLAY_V4_FILE_TEST_FAULT_REWRITE);CHECK(!NativeReplaySchedulerV4_Finalize(&s)&&s.mode==NATIVE_REPLAY_SCHEDULER_V4_POISON);NativeReplaySchedulerV4_Close(&s);CHECK(remove(p)==0);(void)remove(q);puts("native_replay_scheduler_v4_test: passed");return 0;}
