#include "platform/native_replay_v4.h"

#include <string.h>

static int EqId(const struct NativeIdentityV1 *a, const struct NativeIdentityV1 *b) { return a && b && memcmp(a, b, sizeof(*a)) == 0; }
static int EqConfigIdentity(const struct NativeReplayV4Header *h) { return h && memcmp(h->identity.build,h->config.buildIdentity,32)==0 && memcmp(h->identity.content,h->config.contentIdentity,32)==0; }
static int WObs(struct NativeCodecWriter *w,const struct NativeReplayV2FrameObservation *v) { const int32_t *s=&v->frameTimer; const uint32_t *u=&v->mixRandomNumber; for(uint32_t i=0;i<10;i++)if(!NativeCodecWriter_WriteS32(w,s[i]))return 0;for(uint32_t i=0;i<6;i++)if(!NativeCodecWriter_WriteU32(w,u[i]))return 0;return 1; }
static int RObs(struct NativeCodecReader *r,struct NativeReplayV2FrameObservation *v) { int32_t *s=&v->frameTimer; uint32_t *u=&v->mixRandomNumber; for(uint32_t i=0;i<10;i++)if(!NativeCodecReader_ReadS32(r,&s[i]))return 0;for(uint32_t i=0;i<6;i++)if(!NativeCodecReader_ReadU32(r,&u[i]))return 0;return 1; }
static int WPad(struct NativeCodecWriter *w,const struct NativeReplayV2Pad *p) { return NativeCodecWriter_WriteU8(w,p->status)&&NativeCodecWriter_WriteU8(w,p->id)&&NativeCodecWriter_WriteBytes(w,p->buttons,2)&&NativeCodecWriter_WriteBytes(w,p->analog,4)&&NativeCodecWriter_WriteU8(w,p->connected); }
static int RPad(struct NativeCodecReader *r,struct NativeReplayV2Pad *p) { return NativeCodecReader_ReadU8(r,&p->status)&&NativeCodecReader_ReadU8(r,&p->id)&&NativeCodecReader_ReadBytes(r,p->buttons,2)&&NativeCodecReader_ReadBytes(r,p->analog,4)&&NativeCodecReader_ReadU8(r,&p->connected); }
static int ReadyW(const struct NativeCodecWriter *w,size_t n) { return w&&!w->failed&&w->offset<=w->capacity&&n<=w->capacity-w->offset; }
static int ReadyR(const struct NativeCodecReader *r,size_t n) { return r&&!r->failed&&r->offset<=r->size&&n<=r->size-r->offset; }

void NativeReplayV4Header_Init(struct NativeReplayV4Header *h) { if(h)memset(h,0,sizeof(*h)); }
int NativeReplayV4Header_Validate(const struct NativeReplayV4Header *h) { return h&&(h->flags&~NATIVE_REPLAY_V4_HEADER_KNOWN_FLAGS)==0&&NativeMatchConfigV1_Validate(&h->config)&&EqConfigIdentity(h); }
size_t NativeReplayV4Header_EncodedSize(void) { return NATIVE_REPLAY_V4_HEADER_BYTES; }
size_t NativeReplayV4Frame_EncodedSize(void) { return NATIVE_REPLAY_V4_FRAME_BYTES; }
int NativeReplayV4_StreamSize(const struct NativeReplayV4Header *h,size_t *n) { if(!NativeReplayV4Header_Validate(h)||!n||h->frameCount>(SIZE_MAX-NATIVE_REPLAY_V4_HEADER_BYTES)/NATIVE_REPLAY_V4_FRAME_BYTES)return 0;*n=NATIVE_REPLAY_V4_HEADER_BYTES+(size_t)h->frameCount*NATIVE_REPLAY_V4_FRAME_BYTES;return 1; }
int NativeReplayV4Header_Encode(struct NativeCodecWriter *w,const struct NativeReplayV4Header *h)
{
	struct NativeCodecWriter e; uint8_t digest[32]; if(!NativeReplayV4Header_Validate(h)||!NativeMatchConfigV1_Digest(&h->config,digest)||!ReadyW(w,NATIVE_REPLAY_V4_HEADER_BYTES))return 0;e=*w;
	if(!NativeCodecWriter_WriteU32(&e,NATIVE_REPLAY_V4_FILE_MAGIC)||!NativeCodecWriter_WriteU32(&e,NATIVE_REPLAY_V4_FORMAT_VERSION)||!NativeCodecWriter_WriteU32(&e,NATIVE_REPLAY_V4_HEADER_BYTES)||!NativeCodecWriter_WriteU32(&e,NATIVE_REPLAY_V4_FRAME_BYTES)||!NativeCodecWriter_WriteU32(&e,h->flags)||!NativeCodecWriter_WriteU32(&e,h->frameCount)||!NativeCodecWriter_WriteU32(&e,NATIVE_CANONICAL_STATE_V4_SCHEMA_VERSION)||!NativeCodecWriter_WriteU32(&e,NATIVE_CANONICAL_REPLAY_V4_FORMAT_VERSION)||!NativeCodecWriter_WriteU32(&e,NATIVE_CANONICAL_DOMAIN_COUNT)||!NativeCodecWriter_WriteU32(&e,(uint32_t)NativeCanonicalStateV4_EncodedSize())||!NativeCodecWriter_WriteU32(&e,NATIVE_REPLAY_V2_PROFILE_NTSC_U)||!NativeCodecWriter_WriteU32(&e,NATIVE_REPLAY_V2_TICK_RATE)||!NativeCodecWriter_WriteU32(&e,NATIVE_REPLAY_V2_ELAPSED_TICK_MS)||!NativeCodecWriter_WriteU64(&e,NATIVE_REPLAY_V2_VBLANK_CYCLES)||!NativeCodecWriter_WriteU64(&e,NATIVE_REPLAY_V2_GPU_CLOCK_HZ)||!NativeCodecWriter_WriteU32(&e,NATIVE_REPLAY_V2_PAD_COUNT)||!NativeCodecWriter_WriteU32(&e,NATIVE_REPLAY_V2_MAX_VSYNC_PACKETS)||!NativeCodecWriter_WriteBytes(&e,h->identity.build,32)||!NativeCodecWriter_WriteBytes(&e,h->identity.content,32)||!NativeMatchConfigV1_Encode(&e,&h->config)||!NativeCodecWriter_WriteBytes(&e,digest,sizeof(digest)))return 0;*w=e;return 1;
}
int NativeReplayV4Header_Decode(struct NativeCodecReader *r,const struct NativeIdentityV1 *id,struct NativeReplayV4Header *h)
{
	struct NativeCodecReader e,cfg;struct NativeReplayV4Header d;uint32_t v[15];uint64_t a,b;uint8_t got[32],want[32];if(!id||!h||!ReadyR(r,NATIVE_REPLAY_V4_HEADER_BYTES))return 0;memset(&d,0,sizeof(d));e=*r;for(uint32_t i=0;i<13;i++)if(!NativeCodecReader_ReadU32(&e,&v[i]))return 0;if(!NativeCodecReader_ReadU64(&e,&a)||!NativeCodecReader_ReadU64(&e,&b)||!NativeCodecReader_ReadU32(&e,&v[13])||!NativeCodecReader_ReadU32(&e,&v[14])||!NativeCodecReader_ReadBytes(&e,d.identity.build,32)||!NativeCodecReader_ReadBytes(&e,d.identity.content,32))return 0;cfg=e; if(!NativeCodecReader_Remaining(&cfg) || NativeCodecReader_Remaining(&cfg)<256+32)return 0; cfg.size=cfg.offset+256; if(!NativeMatchConfigV1_Decode(&cfg,&d.config)||cfg.offset!=e.offset+256)return 0;e.offset=cfg.offset;if(!NativeCodecReader_ReadBytes(&e,got,32)||!NativeMatchConfigV1_Digest(&d.config,want))return 0;d.flags=v[4];d.frameCount=v[5];if(v[0]!=NATIVE_REPLAY_V4_FILE_MAGIC||v[1]!=NATIVE_REPLAY_V4_FORMAT_VERSION||v[2]!=NATIVE_REPLAY_V4_HEADER_BYTES||v[3]!=NATIVE_REPLAY_V4_FRAME_BYTES||(d.flags&~NATIVE_REPLAY_V4_HEADER_KNOWN_FLAGS)||v[6]!=NATIVE_CANONICAL_STATE_V4_SCHEMA_VERSION||v[7]!=NATIVE_CANONICAL_REPLAY_V4_FORMAT_VERSION||v[8]!=NATIVE_CANONICAL_DOMAIN_COUNT||v[9]!=NativeCanonicalStateV4_EncodedSize()||v[10]!=NATIVE_REPLAY_V2_PROFILE_NTSC_U||v[11]!=NATIVE_REPLAY_V2_TICK_RATE||v[12]!=NATIVE_REPLAY_V2_ELAPSED_TICK_MS||a!=NATIVE_REPLAY_V2_VBLANK_CYCLES||b!=NATIVE_REPLAY_V2_GPU_CLOCK_HZ||v[13]!=NATIVE_REPLAY_V2_PAD_COUNT||v[14]!=NATIVE_REPLAY_V2_MAX_VSYNC_PACKETS||!EqId(&d.identity,id)||!EqConfigIdentity(&d)||memcmp(got,want,32))return 0;*r=e;*h=d;return 1;
}
int NativeReplayV4Frame_Validate(const struct NativeReplayV4Header *h,const struct NativeReplayV4Frame *f)
{
	uint32_t total=0;uint8_t digest[32];if(!NativeReplayV4Header_Validate(h)||!f||f->padCount!=NATIVE_REPLAY_V2_PAD_COUNT||f->vsyncPacketCount>NATIVE_REPLAY_V2_MAX_VSYNC_PACKETS||!NativeMatchConfigV1_Digest(&h->config,digest)||!NativeCanonicalStateV4_Validate(&f->canonical)||!EqId(&h->identity,&f->canonical.identity)||memcmp(digest,f->canonical.configDigest,32)||f->canonical.frameNumber!=f->replayFrame)return 0;for(uint32_t i=0;i<f->vsyncPacketCount;i++){if(!f->vsyncPackets[i]||UINT32_MAX-total<f->vsyncPackets[i])return 0;total+=f->vsyncPackets[i];}for(uint32_t i=f->vsyncPacketCount;i<NATIVE_REPLAY_V2_MAX_VSYNC_PACKETS;i++)if(f->vsyncPackets[i])return 0;return total==f->vsyncTotal;
}
int NativeReplayV4Frame_Encode(struct NativeCodecWriter *w,const struct NativeReplayV4Header *h,const struct NativeReplayV4Frame *f)
{
	struct NativeCodecWriter e;if(!NativeReplayV4Frame_Validate(h,f)||!ReadyW(w,NATIVE_REPLAY_V4_FRAME_BYTES))return 0;e=*w;if(!NativeCodecWriter_WriteU32(&e,NATIVE_REPLAY_V4_FRAME_MAGIC)||!NativeCodecWriter_WriteU32(&e,NATIVE_REPLAY_V4_FRAME_BYTES)||!NativeCodecWriter_WriteU32(&e,f->replayFrame)||!WObs(&e,&f->begin)||!WObs(&e,&f->end)||!NativeCodecWriter_WriteU32(&e,f->padCount))return 0;for(uint32_t i=0;i<4;i++)if(!WPad(&e,&f->pads[i]))return 0;if(!NativeCodecWriter_WriteU32(&e,f->vsyncTotal)||!NativeCodecWriter_WriteU32(&e,f->vsyncPacketCount))return 0;for(uint32_t i=0;i<64;i++)if(!NativeCodecWriter_WriteU16(&e,f->vsyncPackets[i]))return 0;if(!NativeCodecWriter_WriteU32(&e,(uint32_t)NativeCanonicalStateV4_EncodedSize())||!NativeCanonicalStateV4_Encode(&e,&f->canonical))return 0;*w=e;return 1;
}
int NativeReplayV4Frame_Decode(struct NativeCodecReader *r,const struct NativeReplayV4Header *h,const struct NativeIdentityV1 *id,struct NativeReplayV4Frame *f)
{
	struct NativeCodecReader e;struct NativeReplayV4Frame d;uint32_t magic,n,cn;uint8_t digest[32];if(!id||!f||!NativeReplayV4Header_Validate(h)||!EqId(&h->identity,id)||!NativeMatchConfigV1_Digest(&h->config,digest)||!ReadyR(r,NATIVE_REPLAY_V4_FRAME_BYTES))return 0;memset(&d,0,sizeof(d));e=*r;if(!NativeCodecReader_ReadU32(&e,&magic)||!NativeCodecReader_ReadU32(&e,&n)||!NativeCodecReader_ReadU32(&e,&d.replayFrame)||magic!=NATIVE_REPLAY_V4_FRAME_MAGIC||n!=NATIVE_REPLAY_V4_FRAME_BYTES||!RObs(&e,&d.begin)||!RObs(&e,&d.end)||!NativeCodecReader_ReadU32(&e,&d.padCount))return 0;for(uint32_t i=0;i<4;i++)if(!RPad(&e,&d.pads[i]))return 0;if(!NativeCodecReader_ReadU32(&e,&d.vsyncTotal)||!NativeCodecReader_ReadU32(&e,&d.vsyncPacketCount))return 0;for(uint32_t i=0;i<64;i++)if(!NativeCodecReader_ReadU16(&e,&d.vsyncPackets[i]))return 0;if(!NativeCodecReader_ReadU32(&e,&cn)||cn!=NativeCanonicalStateV4_EncodedSize()||!NativeCanonicalStateV4_Decode(&e,id,digest,&d.canonical)||!NativeReplayV4Frame_Validate(h,&d))return 0;*r=e;*f=d;return 1;
}
