#include "platform/native_replay_scheduler_v4.h"
#include <string.h>

static int EqIdentity(const struct NativeIdentityV1 *a,const struct NativeIdentityV1 *b) { return a&&b&&memcmp(a->build,b->build,32)==0&&memcmp(a->content,b->content,32)==0; }
static int EqObs(const struct NativeReplayV2FrameObservation *a,const struct NativeReplayV2FrameObservation *b) { return a&&b&&memcmp(a,b,sizeof(*a))==0; }
static int Poison(struct NativeReplaySchedulerV4 *s) { if(s) s->mode=NATIVE_REPLAY_SCHEDULER_V4_POISON; return 0; }
static int IdentityOK(const struct NativeIdentityV1 *i) { uint8_t any=0;if(!i)return 0;for(uint32_t n=0;n<32;n++)any|=i->build[n]|i->content[n];return any!=0; }
static int RequestOK(const struct NativeReplaySchedulerV4Request *r) { uint8_t d[32]; return r&&IdentityOK(&r->identity)&&NativeMatchConfigV1_Validate(&r->config)&&NativeMatchConfigV1_Digest(&r->config,d)&&memcmp(d,r->configDigest,32)==0; }
static int SessionRequestOK(const struct NativeReplaySchedulerV4 *s,const struct NativeReplaySchedulerV4Request *r) { uint8_t d[32];const struct NativeReplayV4Header *h;if(!s||!RequestOK(r))return 0;h=s->mode==NATIVE_REPLAY_SCHEDULER_V4_RECORD?&s->record.header:&s->playback.header;return EqIdentity(&r->identity,&h->identity)&&NativeMatchConfigV1_Digest(&h->config,d)&&memcmp(d,r->configDigest,32)==0; }
static int CanonicalOK(const struct NativeReplaySchedulerV4Request *r,const struct NativeCanonicalStateV4 *s) { struct NativeCanonicalStateV4 c; if(!r||!s||s->frameNumber!=r->replayFrame||!EqIdentity(&s->identity,&r->identity)||memcmp(s->configDigest,r->configDigest,32)||!NativeCanonicalStateV4_Validate(s)||s->deterministicRng.masterSeed!=r->config.masterSeed||s->deterministicRng.derivationVersion!=r->config.rngDerivationVersion)return 0;c=*s;return NativeCanonicalStateV4_ComputeDigests(&c)&&memcmp(c.domainDigests,s->domainDigests,sizeof(c.domainDigests))==0&&c.combinedDigest==s->combinedDigest; }
static int Match(struct NativeReplaySchedulerV4 *s,uint32_t mask,uint32_t domains) { if(!s)return 0;if(s->mode!=NATIVE_REPLAY_SCHEDULER_V4_MISMATCH){memset(&s->mismatch,0,sizeof(s->mismatch));s->mismatch.mask=mask;s->mismatch.canonicalDomainMask=domains;s->mismatch.expectedFrame=s->pending.replayFrame;s->mismatch.liveFrame=s->request.replayFrame;s->mode=NATIVE_REPLAY_SCHEDULER_V4_MISMATCH;}return 0; }
void NativeReplaySchedulerV4_Init(struct NativeReplaySchedulerV4 *s) { if(!s)return;memset(s,0,sizeof(*s));NativeReplayV4Record_Init(&s->record);NativeReplayV4Playback_Init(&s->playback); }
int NativeReplaySchedulerV4_OpenRecord(struct NativeReplaySchedulerV4 *s,const char *p,const struct NativeIdentityV1 *i,const struct NativeMatchConfigV1 *c) { if(!s||s->mode!=NATIVE_REPLAY_SCHEDULER_V4_IDLE||!NativeReplayV4Record_Open(&s->record,p,i,c))return Poison(s);s->mode=NATIVE_REPLAY_SCHEDULER_V4_RECORD;return 1; }
int NativeReplaySchedulerV4_OpenPlayback(struct NativeReplaySchedulerV4 *s,const char *p,const struct NativeIdentityV1 *i,const struct NativeMatchConfigV1 *c) { struct NativeReplayV4Header h;if(!s||s->mode!=NATIVE_REPLAY_SCHEDULER_V4_IDLE||!NativeReplayV4Playback_Open(&s->playback,p,i,c,&h))return Poison(s);s->mode=NATIVE_REPLAY_SCHEDULER_V4_PLAYBACK;return 1; }
int NativeReplaySchedulerV4_BeginFrame(struct NativeReplaySchedulerV4 *s,const struct NativeReplaySchedulerV4Request *r,const struct NativeReplayV2FrameObservation *b,const struct NativeReplayV2Pad p[4]) { struct NativeReplayV4Frame f;if(!s||!r||!b||!p||s->frameOpen||!SessionRequestOK(s,r)||(s->mode!=NATIVE_REPLAY_SCHEDULER_V4_RECORD&&s->mode!=NATIVE_REPLAY_SCHEDULER_V4_PLAYBACK))return Poison(s);if(s->mode==NATIVE_REPLAY_SCHEDULER_V4_PLAYBACK){if(NativeReplayV4Playback_ReadNext(&s->playback,&f)!=NATIVE_REPLAY_V4_READ_FRAME||f.replayFrame!=r->replayFrame||!EqIdentity(&f.canonical.identity,&r->identity)||memcmp(f.canonical.configDigest,r->configDigest,32))return Poison(s);s->pending=f;s->beginMismatch=!EqObs(&f.begin,b);}else{memset(&s->pending,0,sizeof(s->pending));s->pending.replayFrame=r->replayFrame;s->pending.begin=*b;s->pending.padCount=4;memcpy(s->pending.pads,p,sizeof(s->pending.pads));}s->request=*r;s->frameOpen=1;s->submitted=0;s->elapsedTaken=0;s->vsyncOverflow=0;s->vsyncConsumed=0;return 1; }
int NativeReplaySchedulerV4_ConsumeVSync(struct NativeReplaySchedulerV4 *s,uint16_t *p) { uint32_t n;if(!s||!p||!s->frameOpen)return Poison(s);n=s->pending.vsyncPacketCount;if(s->mode==NATIVE_REPLAY_SCHEDULER_V4_RECORD){if(n>=64||!*p)return Poison(s);s->pending.vsyncPackets[n]=*p;s->pending.vsyncPacketCount=n+1;s->pending.vsyncTotal+=*p;return 1;}if(s->mode!=NATIVE_REPLAY_SCHEDULER_V4_PLAYBACK)return Poison(s);if(s->vsyncConsumed>=n){s->vsyncOverflow=1;return 0;}*p=s->pending.vsyncPackets[s->vsyncConsumed++];return 1; }
int NativeReplaySchedulerV4_ConsumeElapsed(struct NativeReplaySchedulerV4 *s,uint32_t *e) { if(!s||!e||!s->frameOpen||s->elapsedTaken)return Poison(s);s->elapsedTaken=1;if(s->mode==NATIVE_REPLAY_SCHEDULER_V4_PLAYBACK)*e=s->pending.end.elapsedTimeMS;return s->mode==NATIVE_REPLAY_SCHEDULER_V4_RECORD||s->mode==NATIVE_REPLAY_SCHEDULER_V4_PLAYBACK; }
int NativeReplaySchedulerV4_SubmitCanonical(struct NativeReplaySchedulerV4 *s,const struct NativeCanonicalStateV4 *c) { if(!s||!s->frameOpen||s->submitted||!CanonicalOK(&s->request,c))return Poison(s);if(s->mode==NATIVE_REPLAY_SCHEDULER_V4_RECORD)s->pending.canonical=*c;else if(s->mode==NATIVE_REPLAY_SCHEDULER_V4_PLAYBACK)s->submittedCanonical=*c;else return Poison(s);s->submitted=1;return 1; }
int NativeReplaySchedulerV4_EndFrame(struct NativeReplaySchedulerV4 *s,const struct NativeReplayV2FrameObservation *e) { uint32_t mask=0,domains=0;if(!s||!e||!s->frameOpen||!s->submitted)return Poison(s);if(s->mode==NATIVE_REPLAY_SCHEDULER_V4_RECORD){s->pending.end=*e;if(!s->elapsedTaken||!NativeReplayV4Record_AppendFrame(&s->record,&s->pending))return Poison(s);s->frameOpen=0;return 1;}if(s->mode!=NATIVE_REPLAY_SCHEDULER_V4_PLAYBACK)return Poison(s);if(s->beginMismatch||!EqObs(&s->pending.end,e))mask|=NATIVE_REPLAY_SCHEDULER_V4_MISMATCH_OBSERVATION;if(!s->elapsedTaken||s->vsyncConsumed!=s->pending.vsyncPacketCount||s->vsyncOverflow)mask|=NATIVE_REPLAY_SCHEDULER_V4_MISMATCH_VSYNC;if(memcmp(s->pending.pads,s->submittedCanonical.input.pads,sizeof(s->pending.pads))!=0)mask|=NATIVE_REPLAY_SCHEDULER_V4_MISMATCH_PAD;for(uint32_t i=0;i<6;i++)if(s->pending.canonical.domainDigests[i]!=s->submittedCanonical.domainDigests[i])domains|=1u<<i;if(domains)mask|=NATIVE_REPLAY_SCHEDULER_V4_MISMATCH_CANONICAL_DOMAIN;if(s->pending.canonical.combinedDigest!=s->submittedCanonical.combinedDigest)mask|=NATIVE_REPLAY_SCHEDULER_V4_MISMATCH_COMBINED;s->frameOpen=0;if(mask)return Match(s,mask,domains);return 1; }
int NativeReplaySchedulerV4_Finalize(struct NativeReplaySchedulerV4 *s) { if(!s||s->mode!=NATIVE_REPLAY_SCHEDULER_V4_RECORD||s->frameOpen||s->record.failed||!NativeReplayV4Record_Finalize(&s->record))return Poison(s);s->mode=NATIVE_REPLAY_SCHEDULER_V4_IDLE;return 1; }
void NativeReplaySchedulerV4_Close(struct NativeReplaySchedulerV4 *s) { if(!s)return;NativeReplayV4Record_Close(&s->record);NativeReplayV4Playback_Close(&s->playback);memset(s,0,sizeof(*s)); }
const struct NativeReplaySchedulerV4MismatchReport *NativeReplaySchedulerV4_FirstMismatch(const struct NativeReplaySchedulerV4 *s) { return s&&s->mode==NATIVE_REPLAY_SCHEDULER_V4_MISMATCH?&s->mismatch:NULL; }
