#include "platform/native_replay_v3.h"

#include <string.h>

#define V3_OBS_BYTES 64u

static int EqId(const struct NativeIdentityV1 *a,const struct NativeIdentityV1 *b){return memcmp(a->build,b->build,NATIVE_IDENTITY_DIGEST_BYTES)==0&&memcmp(a->content,b->content,NATIVE_IDENTITY_DIGEST_BYTES)==0;}
static int WObs(struct NativeCodecWriter *w,const struct NativeReplayV2FrameObservation *v){return NativeCodecWriter_WriteS32(w,v->frameTimer)&&NativeCodecWriter_WriteS32(w,v->frameCounter)&&NativeCodecWriter_WriteS32(w,v->timer)&&NativeCodecWriter_WriteS32(w,v->framesInThisLEV)&&NativeCodecWriter_WriteS32(w,v->elapsedTimeMS)&&NativeCodecWriter_WriteS32(w,v->msInThisLEV)&&NativeCodecWriter_WriteS32(w,v->elapsedEventTime)&&NativeCodecWriter_WriteS32(w,v->mainGameState)&&NativeCodecWriter_WriteS32(w,v->loadingStage)&&NativeCodecWriter_WriteS32(w,v->levelID)&&NativeCodecWriter_WriteU32(w,v->mixRandomNumber)&&NativeCodecWriter_WriteU32(w,v->audioRNG)&&NativeCodecWriter_WriteU32(w,v->deadcoed0)&&NativeCodecWriter_WriteU32(w,v->deadcoed1)&&NativeCodecWriter_WriteU32(w,v->advRng0)&&NativeCodecWriter_WriteU32(w,v->advRng1);}
static int RObs(struct NativeCodecReader *r,struct NativeReplayV2FrameObservation *v){return NativeCodecReader_ReadS32(r,&v->frameTimer)&&NativeCodecReader_ReadS32(r,&v->frameCounter)&&NativeCodecReader_ReadS32(r,&v->timer)&&NativeCodecReader_ReadS32(r,&v->framesInThisLEV)&&NativeCodecReader_ReadS32(r,&v->elapsedTimeMS)&&NativeCodecReader_ReadS32(r,&v->msInThisLEV)&&NativeCodecReader_ReadS32(r,&v->elapsedEventTime)&&NativeCodecReader_ReadS32(r,&v->mainGameState)&&NativeCodecReader_ReadS32(r,&v->loadingStage)&&NativeCodecReader_ReadS32(r,&v->levelID)&&NativeCodecReader_ReadU32(r,&v->mixRandomNumber)&&NativeCodecReader_ReadU32(r,&v->audioRNG)&&NativeCodecReader_ReadU32(r,&v->deadcoed0)&&NativeCodecReader_ReadU32(r,&v->deadcoed1)&&NativeCodecReader_ReadU32(r,&v->advRng0)&&NativeCodecReader_ReadU32(r,&v->advRng1);}
static int WPad(struct NativeCodecWriter *w,const struct NativeReplayV2Pad *p){return NativeCodecWriter_WriteU8(w,p->status)&&NativeCodecWriter_WriteU8(w,p->id)&&NativeCodecWriter_WriteBytes(w,p->buttons,2)&&NativeCodecWriter_WriteBytes(w,p->analog,4)&&NativeCodecWriter_WriteU8(w,p->connected);}
static int RPad(struct NativeCodecReader *r,struct NativeReplayV2Pad *p){return NativeCodecReader_ReadU8(r,&p->status)&&NativeCodecReader_ReadU8(r,&p->id)&&NativeCodecReader_ReadBytes(r,p->buttons,2)&&NativeCodecReader_ReadBytes(r,p->analog,4)&&NativeCodecReader_ReadU8(r,&p->connected);}
static int ReadyW(const struct NativeCodecWriter *w,size_t n){return w!=NULL&&!w->failed&&w->offset<=w->capacity&&n<=w->capacity-w->offset;}
static int ReadyR(const struct NativeCodecReader *r,size_t n){return r!=NULL&&!r->failed&&r->offset<=r->size&&n<=r->size-r->offset;}

void NativeReplayV3Header_Init(struct NativeReplayV3Header *h){if(h!=NULL)memset(h,0,sizeof(*h));}
int NativeReplayV3Header_Validate(const struct NativeReplayV3Header *h){return h!=NULL&&(h->flags&~NATIVE_REPLAY_V3_HEADER_KNOWN_FLAGS)==0;}
size_t NativeReplayV3Header_EncodedSize(void){return NATIVE_REPLAY_V3_HEADER_BYTES;}
size_t NativeReplayV3Frame_EncodedSize(void){return NATIVE_REPLAY_V3_FRAME_BYTES;}
int NativeReplayV3_StreamSize(const struct NativeReplayV3Header *h,size_t *n){if(!NativeReplayV3Header_Validate(h)||n==NULL||h->frameCount>(SIZE_MAX-NATIVE_REPLAY_V3_HEADER_BYTES)/NATIVE_REPLAY_V3_FRAME_BYTES)return 0;*n=NATIVE_REPLAY_V3_HEADER_BYTES+(size_t)h->frameCount*NATIVE_REPLAY_V3_FRAME_BYTES;return 1;}
int NativeReplayV3Header_Encode(struct NativeCodecWriter *w,const struct NativeReplayV3Header *h)
{
	struct NativeCodecWriter e;if(!NativeReplayV3Header_Validate(h)||!ReadyW(w,NATIVE_REPLAY_V3_HEADER_BYTES))return 0;e=*w;
	if(!NativeCodecWriter_WriteU32(&e,NATIVE_REPLAY_V3_FILE_MAGIC)||!NativeCodecWriter_WriteU32(&e,NATIVE_REPLAY_V3_FORMAT_VERSION)||!NativeCodecWriter_WriteU32(&e,NATIVE_REPLAY_V3_HEADER_BYTES)||!NativeCodecWriter_WriteU32(&e,NATIVE_REPLAY_V3_FRAME_BYTES)||!NativeCodecWriter_WriteU32(&e,h->flags)||!NativeCodecWriter_WriteU32(&e,h->frameCount)||!NativeCodecWriter_WriteU32(&e,NATIVE_CANONICAL_STATE_V3_SCHEMA_VERSION)||!NativeCodecWriter_WriteU32(&e,NATIVE_CANONICAL_REPLAY_V3_FORMAT_VERSION)||!NativeCodecWriter_WriteU32(&e,NATIVE_CANONICAL_DOMAIN_COUNT)||!NativeCodecWriter_WriteU32(&e,(uint32_t)NativeCanonicalStateV3_EncodedSize())||!NativeCodecWriter_WriteU32(&e,NATIVE_REPLAY_V2_PROFILE_NTSC_U)||!NativeCodecWriter_WriteU32(&e,NATIVE_REPLAY_V2_TICK_RATE)||!NativeCodecWriter_WriteU32(&e,NATIVE_REPLAY_V2_ELAPSED_TICK_MS)||!NativeCodecWriter_WriteU64(&e,NATIVE_REPLAY_V2_VBLANK_CYCLES)||!NativeCodecWriter_WriteU64(&e,NATIVE_REPLAY_V2_GPU_CLOCK_HZ)||!NativeCodecWriter_WriteU32(&e,NATIVE_REPLAY_V2_PAD_COUNT)||!NativeCodecWriter_WriteU32(&e,NATIVE_REPLAY_V2_MAX_VSYNC_PACKETS)||!NativeCodecWriter_WriteBytes(&e,h->identity.build,NATIVE_IDENTITY_DIGEST_BYTES)||!NativeCodecWriter_WriteBytes(&e,h->identity.content,NATIVE_IDENTITY_DIGEST_BYTES))return 0;*w=e;return 1;
}
int NativeReplayV3Header_Decode(struct NativeCodecReader *r,const struct NativeIdentityV1 *id,struct NativeReplayV3Header *h)
{
	struct NativeCodecReader e;struct NativeReplayV3Header d;uint32_t v[15];uint64_t a,b;if(id==NULL||h==NULL||!ReadyR(r,NATIVE_REPLAY_V3_HEADER_BYTES))return 0;e=*r;for(uint32_t i=0;i<13;i++)if(!NativeCodecReader_ReadU32(&e,&v[i]))return 0;if(!NativeCodecReader_ReadU64(&e,&a)||!NativeCodecReader_ReadU64(&e,&b)||!NativeCodecReader_ReadU32(&e,&v[13])||!NativeCodecReader_ReadU32(&e,&v[14])||!NativeCodecReader_ReadBytes(&e,d.identity.build,NATIVE_IDENTITY_DIGEST_BYTES)||!NativeCodecReader_ReadBytes(&e,d.identity.content,NATIVE_IDENTITY_DIGEST_BYTES))return 0;d.flags=v[4];d.frameCount=v[5];if(v[0]!=NATIVE_REPLAY_V3_FILE_MAGIC||v[1]!=NATIVE_REPLAY_V3_FORMAT_VERSION||v[2]!=NATIVE_REPLAY_V3_HEADER_BYTES||v[3]!=NATIVE_REPLAY_V3_FRAME_BYTES||(v[4]&~NATIVE_REPLAY_V3_HEADER_KNOWN_FLAGS)||v[6]!=NATIVE_CANONICAL_STATE_V3_SCHEMA_VERSION||v[7]!=NATIVE_CANONICAL_REPLAY_V3_FORMAT_VERSION||v[8]!=NATIVE_CANONICAL_DOMAIN_COUNT||v[9]!=NativeCanonicalStateV3_EncodedSize()||v[10]!=NATIVE_REPLAY_V2_PROFILE_NTSC_U||v[11]!=NATIVE_REPLAY_V2_TICK_RATE||v[12]!=NATIVE_REPLAY_V2_ELAPSED_TICK_MS||a!=NATIVE_REPLAY_V2_VBLANK_CYCLES||b!=NATIVE_REPLAY_V2_GPU_CLOCK_HZ||v[13]!=NATIVE_REPLAY_V2_PAD_COUNT||v[14]!=NATIVE_REPLAY_V2_MAX_VSYNC_PACKETS||!EqId(&d.identity,id))return 0;*r=e;*h=d;return 1;
}
int NativeReplayV3Frame_Validate(const struct NativeReplayV3Header *h,const struct NativeReplayV3Frame *f)
{
	uint32_t total=0;if(!NativeReplayV3Header_Validate(h)||f==NULL||f->padCount!=NATIVE_REPLAY_V2_PAD_COUNT||f->vsyncPacketCount>NATIVE_REPLAY_V2_MAX_VSYNC_PACKETS||!NativeCanonicalStateV3_Validate(&f->canonical)||!EqId(&h->identity,&f->canonical.identity)||f->canonical.frameNumber!=f->replayFrame)return 0;for(uint32_t i=0;i<f->vsyncPacketCount;i++){if(f->vsyncPackets[i]==0)return 0;total+=f->vsyncPackets[i];}for(uint32_t i=f->vsyncPacketCount;i<NATIVE_REPLAY_V2_MAX_VSYNC_PACKETS;i++)if(f->vsyncPackets[i]!=0)return 0;return total==f->vsyncTotal;
}
int NativeReplayV3Frame_Encode(struct NativeCodecWriter *w,const struct NativeReplayV3Header *h,const struct NativeReplayV3Frame *f)
{
	struct NativeCodecWriter e;if(!NativeReplayV3Frame_Validate(h,f)||!ReadyW(w,NATIVE_REPLAY_V3_FRAME_BYTES))return 0;e=*w;if(!NativeCodecWriter_WriteU32(&e,NATIVE_REPLAY_V3_FRAME_MAGIC)||!NativeCodecWriter_WriteU32(&e,NATIVE_REPLAY_V3_FRAME_BYTES)||!NativeCodecWriter_WriteU32(&e,f->replayFrame)||!WObs(&e,&f->begin)||!WObs(&e,&f->end)||!NativeCodecWriter_WriteU32(&e,f->padCount))return 0;for(uint32_t i=0;i<NATIVE_REPLAY_V2_PAD_COUNT;i++)if(!WPad(&e,&f->pads[i]))return 0;if(!NativeCodecWriter_WriteU32(&e,f->vsyncTotal)||!NativeCodecWriter_WriteU32(&e,f->vsyncPacketCount))return 0;for(uint32_t i=0;i<NATIVE_REPLAY_V2_MAX_VSYNC_PACKETS;i++)if(!NativeCodecWriter_WriteU16(&e,f->vsyncPackets[i]))return 0;if(!NativeCodecWriter_WriteU32(&e,(uint32_t)NativeCanonicalStateV3_EncodedSize())||!NativeCanonicalStateV3_Encode(&e,&f->canonical))return 0;*w=e;return 1;
}
int NativeReplayV3Frame_Decode(struct NativeCodecReader *r,const struct NativeReplayV3Header *h,const struct NativeIdentityV1 *id,struct NativeReplayV3Frame *f)
{
	struct NativeCodecReader e;struct NativeReplayV3Frame d;uint32_t magic,n,cn;if(id==NULL||f==NULL||!NativeReplayV3Header_Validate(h)||!EqId(&h->identity,id)||!ReadyR(r,NATIVE_REPLAY_V3_FRAME_BYTES))return 0;memset(&d,0,sizeof(d));e=*r;if(!NativeCodecReader_ReadU32(&e,&magic)||!NativeCodecReader_ReadU32(&e,&n)||!NativeCodecReader_ReadU32(&e,&d.replayFrame)||magic!=NATIVE_REPLAY_V3_FRAME_MAGIC||n!=NATIVE_REPLAY_V3_FRAME_BYTES||!RObs(&e,&d.begin)||!RObs(&e,&d.end)||!NativeCodecReader_ReadU32(&e,&d.padCount))return 0;for(uint32_t i=0;i<NATIVE_REPLAY_V2_PAD_COUNT;i++)if(!RPad(&e,&d.pads[i]))return 0;if(!NativeCodecReader_ReadU32(&e,&d.vsyncTotal)||!NativeCodecReader_ReadU32(&e,&d.vsyncPacketCount))return 0;for(uint32_t i=0;i<NATIVE_REPLAY_V2_MAX_VSYNC_PACKETS;i++)if(!NativeCodecReader_ReadU16(&e,&d.vsyncPackets[i]))return 0;if(!NativeCodecReader_ReadU32(&e,&cn)||cn!=NativeCanonicalStateV3_EncodedSize()||!NativeCanonicalStateV3_Decode(&e,id,&d.canonical)||!NativeReplayV3Frame_Validate(h,&d))return 0;*r=e;*f=d;return 1;
}
