#include "platform/native_canonical_state_v4.h"
#include <string.h>

#define V4_CONTROL_BYTES 48u
#define V4_RETAIL_RNG_BYTES 20u
#define V4_RNG_BYTES (4u + V4_RETAIL_RNG_BYTES + NATIVE_DETERMINISTIC_RNG_BANK_V1_ENCODED_BYTES)
#define V4_INPUT_BYTES 40u
#define V4_WORLD_BYTES (8u + 8u + NATIVE_CANONICAL_WORLD_COUNTERS_V1_ENCODED_BYTES + 8u + NATIVE_CANONICAL_WORLD_V1_MINE_SLOT_BYTES)
#define V4_HEADER_BYTES 116u
#define V4_DOMAIN_BYTES 16u
#define V4_STATE_BYTES (V4_HEADER_BYTES + V4_CONTROL_BYTES + V4_RNG_BYTES + V4_INPUT_BYTES + NATIVE_CANONICAL_DRIVERS_SUMMARY_BYTES + V4_WORLD_BYTES + NATIVE_CANONICAL_TOPOLOGY_SUMMARY_BYTES + NATIVE_CANONICAL_DOMAIN_COUNT * V4_DOMAIN_BYTES + 8u)

static size_t Size(uint32_t id) { switch (id) { case 1:return V4_CONTROL_BYTES; case 2:return V4_RNG_BYTES; case 3:return V4_INPUT_BYTES; case 4:return NATIVE_CANONICAL_DRIVERS_SUMMARY_BYTES; case 5:return V4_WORLD_BYTES; case 6:return NATIVE_CANONICAL_TOPOLOGY_SUMMARY_BYTES; default:return SIZE_MAX; } }
static int ControlW(struct NativeCodecWriter *w,const struct NativeCanonicalControlV1 *v) { const int32_t *p=&v->frameTimer; for(uint32_t i=0;i<12;i++)if(!NativeCodecWriter_WriteS32(w,p[i]))return 0;return 1; }
static int ControlR(struct NativeCodecReader *r,struct NativeCanonicalControlV1 *v) { int32_t *p=&v->frameTimer; for(uint32_t i=0;i<12;i++)if(!NativeCodecReader_ReadS32(r,&p[i]))return 0;return 1; }
static int RetailW(struct NativeCodecWriter *w,const struct NativeCanonicalRngV1 *v) { const uint32_t *p=&v->mixRandomNumber; for(uint32_t i=0;i<5;i++)if(!NativeCodecWriter_WriteU32(w,p[i]))return 0;return 1; }
static int RetailR(struct NativeCodecReader *r,struct NativeCanonicalRngV1 *v) { uint32_t *p=&v->mixRandomNumber; for(uint32_t i=0;i<5;i++)if(!NativeCodecReader_ReadU32(r,&p[i]))return 0;return 1; }
static int InputW(struct NativeCodecWriter *w,const struct NativeCanonicalInputV1 *v) { if(!NativeCodecWriter_WriteU32(w,v->padCount))return 0;for(uint32_t i=0;i<4;i++)if(!NativeCodecWriter_WriteU8(w,v->pads[i].status)||!NativeCodecWriter_WriteU8(w,v->pads[i].id)||!NativeCodecWriter_WriteBytes(w,v->pads[i].buttons,2)||!NativeCodecWriter_WriteBytes(w,v->pads[i].analog,4)||!NativeCodecWriter_WriteU8(w,v->pads[i].connected))return 0;return 1; }
static int InputR(struct NativeCodecReader *r,struct NativeCanonicalInputV1 *v) { if(!NativeCodecReader_ReadU32(r,&v->padCount)||v->padCount!=4)return 0;for(uint32_t i=0;i<4;i++)if(!NativeCodecReader_ReadU8(r,&v->pads[i].status)||!NativeCodecReader_ReadU8(r,&v->pads[i].id)||!NativeCodecReader_ReadBytes(r,v->pads[i].buttons,2)||!NativeCodecReader_ReadBytes(r,v->pads[i].analog,4)||!NativeCodecReader_ReadU8(r,&v->pads[i].connected))return 0;return 1; }
static int MineW(struct NativeCodecWriter *w,const struct NativeCanonicalWorldMineRegistryV1 *m) { uint8_t b[NATIVE_CANONICAL_WORLD_V1_MINE_SLOT_BYTES]={0};struct NativeCodecWriter x;NativeCodecWriter_Init(&x,b,sizeof(b),NULL);if(!NativeCanonicalWorldMineRegistryV1_Encode(&x,m)||!NativeCodecWriter_WriteBytes(w,b,sizeof(b)))return 0;return 1; }
static int MineR(struct NativeCodecReader *r,struct NativeCanonicalWorldMineRegistryV1 *m) { uint8_t b[NATIVE_CANONICAL_WORLD_V1_MINE_SLOT_BYTES];struct NativeCodecReader x;size_t n;if(!NativeCodecReader_ReadBytes(r,b,sizeof(b)))return 0;NativeCodecReader_Init(&x,b,sizeof(b));if(!NativeCanonicalWorldMineRegistryV1_Decode(&x,m))return 0;n=x.offset;for(;n<sizeof(b);n++)if(b[n])return 0;return 1; }
static int WorldW(struct NativeCodecWriter *w,const struct NativeCanonicalStateV4 *s) { if(!NativeCodecWriter_WriteU32(w,NATIVE_CANONICAL_WORLD_V1_VERSION)||!NativeCodecWriter_WriteU32(w,2)||!NativeCodecWriter_WriteU32(w,NATIVE_CANONICAL_WORLD_V1_COUNTERS_COMPONENT)||!NativeCodecWriter_WriteU32(w,12)||!NativeCanonicalWorldCountersV1_Encode(w,&s->worldCounters)||!NativeCodecWriter_WriteU32(w,NATIVE_CANONICAL_WORLD_V1_MINE_REGISTRY_COMPONENT)||!NativeCodecWriter_WriteU32(w,NATIVE_CANONICAL_WORLD_V1_MINE_SLOT_BYTES)||!MineW(w,&s->mineRegistry))return 0;return 1; }
static int WorldR(struct NativeCodecReader *r,struct NativeCanonicalStateV4 *s) { uint32_t a,b,c,d;if(!NativeCodecReader_ReadU32(r,&a)||!NativeCodecReader_ReadU32(r,&b)||a!=1||b!=2||!NativeCodecReader_ReadU32(r,&a)||!NativeCodecReader_ReadU32(r,&b)||a!=1||b!=12||!NativeCanonicalWorldCountersV1_Decode(r,&s->worldCounters)||!NativeCodecReader_ReadU32(r,&c)||!NativeCodecReader_ReadU32(r,&d)||c!=2||d!=NATIVE_CANONICAL_WORLD_V1_MINE_SLOT_BYTES||!MineR(r,&s->mineRegistry))return 0;return 1; }
static int Payload(const struct NativeCanonicalStateV4 *s,uint32_t id,uint8_t *b,size_t n) { struct NativeCodecWriter w;if(!s||n!=Size(id))return 0;NativeCodecWriter_Init(&w,b,n,NULL);switch(id){case 1:if(!ControlW(&w,&s->control))return 0;break;case 2:if(!NativeCodecWriter_WriteU32(&w,2)||!RetailW(&w,&s->retailRng)||!NativeDeterministicRngBankV1_Encode(&w,&s->deterministicRng))return 0;break;case 3:if(!InputW(&w,&s->input))return 0;break;case 4:if(!NativeCanonicalDriversV1_Encode(&w,&s->drivers))return 0;break;case 5:if(!WorldW(&w,s))return 0;break;case 6:if(!NativeCanonicalTopologyV1_Encode(&w,&s->topology))return 0;break;default:return 0;}return NativeCodecWriter_Ok(&w)&&w.offset==n; }
static int PayloadR(struct NativeCodecReader *r,struct NativeCanonicalStateV4 *s,uint32_t id) { uint32_t v; struct NativeCodecReader bank; switch(id){case 1:return ControlR(r,&s->control);case 2:if(!NativeCodecReader_ReadU32(r,&v)||v!=2||!RetailR(r,&s->retailRng)||NativeCodecReader_Remaining(r)<NATIVE_DETERMINISTIC_RNG_BANK_V1_ENCODED_BYTES)return 0;NativeCodecReader_Init(&bank,r->data+r->offset,NATIVE_DETERMINISTIC_RNG_BANK_V1_ENCODED_BYTES);if(!NativeDeterministicRngBankV1_Decode(&bank,&s->deterministicRng))return 0;r->offset+=NATIVE_DETERMINISTIC_RNG_BANK_V1_ENCODED_BYTES;return 1;case 3:return InputR(r,&s->input);case 4:return NativeCanonicalDriversV1_Decode(r,&s->drivers);case 5:return WorldR(r,s);case 6:return NativeCanonicalTopologyV1_Decode(r,&s->topology);default:return 0;} }
static uint64_t Digest(const uint8_t *b,size_t n) { struct NativeCodecDigest64 d;NativeCodecDigest64_Init(&d);NativeCodecDigest64_Update(&d,b,n);return d.value; }
static uint64_t Combined(const uint64_t *ds) { uint8_t b[72];struct NativeCodecWriter w;NativeCodecWriter_Init(&w,b,sizeof(b),NULL);for(uint32_t i=0;i<6;i++){(void)NativeCodecWriter_WriteU32(&w,NativeCanonicalDomainOrder[i]);(void)NativeCodecWriter_WriteU64(&w,ds[i]);}return Digest(b,sizeof(b)); }
static int Identity(const struct NativeIdentityV1 *a,const struct NativeIdentityV1 *b) { return memcmp(a,b,sizeof(*a))==0; }
void NativeCanonicalStateV4_Init(struct NativeCanonicalStateV4 *s) { if(!s)return;memset(s,0,sizeof(*s));s->schemaVersion=5;s->replayFormatVersion=4;s->domainCount=6;s->input.padCount=4;NativeCanonicalDriversV1_Init(&s->drivers);NativeCanonicalWorldCountersV1_Init(&s->worldCounters);NativeCanonicalWorldMineRegistryV1_Init(&s->mineRegistry);NativeCanonicalTopologyV1_Init(&s->topology);(void)NativeDeterministicRngBankV1_Init(&s->deterministicRng,0,1);(void)NativeCanonicalStateV4_ComputeDigests(s); }
int NativeCanonicalStateV4_Validate(const struct NativeCanonicalStateV4 *s) { return s&&s->schemaVersion==5&&s->replayFormatVersion==4&&s->domainCount==6&&s->input.padCount==4&&NativeCanonicalDriversV1_Validate(&s->drivers)&&NativeDeterministicRngBankV1_Validate(&s->deterministicRng)&&NativeCanonicalWorldCountersV1_Validate(&s->worldCounters)&&NativeCanonicalWorldMineRegistryV1_Validate(&s->mineRegistry)&&NativeCanonicalTopologyV1_Validate(&s->topology); }
int NativeCanonicalStateV4_ComputeDigests(struct NativeCanonicalStateV4 *s) { struct NativeCanonicalStateV4 c;uint8_t b[V4_RNG_BYTES];if(!NativeCanonicalStateV4_Validate(s))return 0;c=*s;for(uint32_t i=0;i<6;i++){size_t n=Size(NativeCanonicalDomainOrder[i]);if(!Payload(s,NativeCanonicalDomainOrder[i],b,n))return 0;c.domainDigests[i]=Digest(b,n);}c.combinedDigest=Combined(c.domainDigests);*s=c;return 1; }
size_t NativeCanonicalStateV4_EncodedSize(void) { return V4_STATE_BYTES; }
int NativeCanonicalStateV4_Encode(struct NativeCodecWriter *w,const struct NativeCanonicalStateV4 *s) { struct NativeCanonicalStateV4 c;struct NativeCodecWriter e;uint8_t b[V4_RNG_BYTES];if(!w||!NativeCanonicalStateV4_Validate(s)||w->failed||w->offset>w->capacity||V4_STATE_BYTES>w->capacity-w->offset)return 0;c=*s;if(!NativeCanonicalStateV4_ComputeDigests(&c)||memcmp(c.domainDigests,s->domainDigests,sizeof(c.domainDigests))||c.combinedDigest!=s->combinedDigest)return 0;e=*w;if(!NativeCodecWriter_WriteU32(&e,NATIVE_CANONICAL_STATE_V4_MAGIC)||!NativeCodecWriter_WriteU32(&e,s->schemaVersion)||!NativeCodecWriter_WriteU32(&e,s->replayFormatVersion)||!NativeCodecWriter_WriteU32(&e,s->domainCount)||!NativeCodecWriter_WriteU32(&e,s->frameNumber)||!NativeCodecWriter_WriteBytes(&e,s->identity.build,32)||!NativeCodecWriter_WriteBytes(&e,s->identity.content,32)||!NativeCodecWriter_WriteBytes(&e,s->configDigest,32))return 0;for(uint32_t i=0;i<6;i++){uint32_t id=NativeCanonicalDomainOrder[i];size_t n=Size(id);if(!Payload(s,id,b,n)||!NativeCodecWriter_WriteU32(&e,id)||!NativeCodecWriter_WriteU32(&e,(uint32_t)n)||!NativeCodecWriter_WriteBytes(&e,b,n)||!NativeCodecWriter_WriteU64(&e,s->domainDigests[i]))return 0;}if(!NativeCodecWriter_WriteU64(&e,s->combinedDigest))return 0;*w=e;return 1; }
int NativeCanonicalStateV4_Decode(struct NativeCodecReader *r,const struct NativeIdentityV1 *id,const uint8_t cfg[32],struct NativeCanonicalStateV4 *s) { struct NativeCodecReader e;struct NativeCanonicalStateV4 d,c;uint8_t b[V4_RNG_BYTES];uint32_t v;if(!r||!id||!cfg||!s||r->failed||r->offset>r->size)return 0;e=*r;NativeCanonicalStateV4_Init(&d);if(!NativeCodecReader_ReadU32(&e,&v)||v!=NATIVE_CANONICAL_STATE_V4_MAGIC||!NativeCodecReader_ReadU32(&e,&d.schemaVersion)||!NativeCodecReader_ReadU32(&e,&d.replayFormatVersion)||!NativeCodecReader_ReadU32(&e,&d.domainCount)||!NativeCodecReader_ReadU32(&e,&d.frameNumber)||!NativeCodecReader_ReadBytes(&e,d.identity.build,32)||!NativeCodecReader_ReadBytes(&e,d.identity.content,32)||!NativeCodecReader_ReadBytes(&e,d.configDigest,32)||!Identity(&d.identity,id)||memcmp(d.configDigest,cfg,32)||!NativeCanonicalStateV4_Validate(&d))return 0;for(uint32_t i=0;i<6;i++){uint32_t got,n,wantId=NativeCanonicalDomainOrder[i];size_t want=Size(wantId);struct NativeCodecReader payload;if(!NativeCodecReader_ReadU32(&e,&got)||!NativeCodecReader_ReadU32(&e,&n)||got!=wantId||n!=want||NativeCodecReader_Remaining(&e)<n)return 0;/* A domain decoder is never allowed to borrow the following digest/domain. */NativeCodecReader_Init(&payload,e.data+e.offset,n);if(!PayloadR(&payload,&d,wantId)||!NativeCodecReader_Ok(&payload)||payload.offset!=n||!Payload(&d,wantId,b,want))return 0;e.offset+=n;if(!NativeCodecReader_ReadU64(&e,&d.domainDigests[i])||d.domainDigests[i]!=Digest(b,want))return 0;}if(!NativeCodecReader_ReadU64(&e,&d.combinedDigest)||NativeCodecReader_Remaining(&e)!=0)return 0;c=d;if(!NativeCanonicalStateV4_ComputeDigests(&c)||memcmp(c.domainDigests,d.domainDigests,sizeof(c.domainDigests))||c.combinedDigest!=d.combinedDigest)return 0;*r=e;*s=d;return 1; }
