#ifndef GAME_MAIN_CANONICAL_TOPOLOGY_LAYOUT_CONTRACT_H
#define GAME_MAIN_CANONICAL_TOPOLOGY_LAYOUT_CONTRACT_H

#include <common.h>

/*
 * Compile-only native-layout contract for the small topology/nav surface
 * already grounded in the source layouts.  It owns no state and exports no
 * API.  In particular, this is not evidence for any unasserted aggregate
 * layout (including Level, GameTracker, or sData).
 *
 * Normative checked-span rule: a later pointer-based consumer must prove the
 * complete half-open byte range [base, base + count * sizeof(element)) is
 * resident and overflow-free before it dereferences any element.  A valid
 * base address alone, or a check of only the first element, is insufficient.
 */

enum MainCanonicalTopologyLayoutContract
{
	MAIN_CANONICAL_TOPOLOGY_LAYOUT_POINTER_BYTES = 0x4,

	MAIN_CANONICAL_TOPOLOGY_LAYOUT_MEMPACK_BYTES = 0x60,
	MAIN_CANONICAL_TOPOLOGY_LAYOUT_MEMPACK_PACK_SIZE_OFFSET = 0x0,
	MAIN_CANONICAL_TOPOLOGY_LAYOUT_MEMPACK_START_OFFSET = 0x4,
	MAIN_CANONICAL_TOPOLOGY_LAYOUT_MEMPACK_END_OFFSET = 0x10,

	MAIN_CANONICAL_TOPOLOGY_LAYOUT_QUAD_BLOCK_BYTES = 0x5c,
	MAIN_CANONICAL_TOPOLOGY_LAYOUT_QUAD_BLOCK_INDEX_OFFSET = 0x0,
	MAIN_CANONICAL_TOPOLOGY_LAYOUT_QUAD_BLOCK_CHECKPOINT_OFFSET = 0x3e,

	MAIN_CANONICAL_TOPOLOGY_LAYOUT_MESH_INFO_BYTES = 0x20,
	MAIN_CANONICAL_TOPOLOGY_LAYOUT_MESH_INFO_QUAD_COUNT_OFFSET = 0x0,
	MAIN_CANONICAL_TOPOLOGY_LAYOUT_MESH_INFO_QUAD_ARRAY_OFFSET = 0xc,

	MAIN_CANONICAL_TOPOLOGY_LAYOUT_CHECKPOINT_NODE_BYTES = 0xc,
	MAIN_CANONICAL_TOPOLOGY_LAYOUT_CHECKPOINT_NODE_POSITION_OFFSET = 0x0,
	MAIN_CANONICAL_TOPOLOGY_LAYOUT_CHECKPOINT_NODE_DISTANCE_OFFSET = 0x6,
	MAIN_CANONICAL_TOPOLOGY_LAYOUT_CHECKPOINT_NODE_FORWARD_OFFSET = 0x8,
	MAIN_CANONICAL_TOPOLOGY_LAYOUT_CHECKPOINT_NODE_RIGHT_OFFSET = 0xb,

	MAIN_CANONICAL_TOPOLOGY_LAYOUT_NAV_FRAME_BYTES = 0x14,
	MAIN_CANONICAL_TOPOLOGY_LAYOUT_NAV_FRAME_POSITION_OFFSET = 0x0,
	MAIN_CANONICAL_TOPOLOGY_LAYOUT_NAV_FRAME_ROTATION_OFFSET = 0x6,
	MAIN_CANONICAL_TOPOLOGY_LAYOUT_NAV_FRAME_DISTANCE_XYZ_OFFSET = 0xa,
	MAIN_CANONICAL_TOPOLOGY_LAYOUT_NAV_FRAME_DISTANCE_XZ_OFFSET = 0xc,
	MAIN_CANONICAL_TOPOLOGY_LAYOUT_NAV_FRAME_FLAGS_OFFSET = 0xe,
	MAIN_CANONICAL_TOPOLOGY_LAYOUT_NAV_FRAME_PATH_CHANGE_OFFSET = 0x10,
	MAIN_CANONICAL_TOPOLOGY_LAYOUT_NAV_FRAME_GO_BACK_OFFSET = 0x12,
	MAIN_CANONICAL_TOPOLOGY_LAYOUT_NAV_FRAME_SPECIAL_BITS_OFFSET = 0x13,

	MAIN_CANONICAL_TOPOLOGY_LAYOUT_NAV_HEADER_BYTES = 0x4c,
	MAIN_CANONICAL_TOPOLOGY_LAYOUT_NAV_HEADER_MAGIC_OFFSET = 0x0,
	MAIN_CANONICAL_TOPOLOGY_LAYOUT_NAV_HEADER_POINT_COUNT_OFFSET = 0x2,
	MAIN_CANONICAL_TOPOLOGY_LAYOUT_NAV_HEADER_FIRST_POSITION_Y_OFFSET = 0x4,
	MAIN_CANONICAL_TOPOLOGY_LAYOUT_NAV_HEADER_LAST_OFFSET = 0x8,
	MAIN_CANONICAL_TOPOLOGY_LAYOUT_NAV_HEADER_RAMP_PHYS_1_OFFSET = 0xc,
	MAIN_CANONICAL_TOPOLOGY_LAYOUT_NAV_HEADER_RAMP_PHYS_2_OFFSET = 0x2c,

	MAIN_CANONICAL_TOPOLOGY_LAYOUT_LEVEL_MESH_OFFSET = 0x0,
	MAIN_CANONICAL_TOPOLOGY_LAYOUT_LEVEL_RESTART_COUNT_OFFSET = 0x148,
	MAIN_CANONICAL_TOPOLOGY_LAYOUT_LEVEL_RESTART_POINTS_OFFSET = 0x14c,
	MAIN_CANONICAL_TOPOLOGY_LAYOUT_LEVEL_NAV_TABLE_OFFSET = 0x188
};

CTR_STATIC_ASSERT(sizeof(void *) == MAIN_CANONICAL_TOPOLOGY_LAYOUT_POINTER_BYTES);

CTR_STATIC_ASSERT(sizeof(struct Mempack) == MAIN_CANONICAL_TOPOLOGY_LAYOUT_MEMPACK_BYTES);
CTR_STATIC_ASSERT(offsetof(struct Mempack, packSize) == MAIN_CANONICAL_TOPOLOGY_LAYOUT_MEMPACK_PACK_SIZE_OFFSET);
CTR_STATIC_ASSERT(offsetof(struct Mempack, start) == MAIN_CANONICAL_TOPOLOGY_LAYOUT_MEMPACK_START_OFFSET);
CTR_STATIC_ASSERT(offsetof(struct Mempack, endOfMemory) == MAIN_CANONICAL_TOPOLOGY_LAYOUT_MEMPACK_END_OFFSET);

CTR_STATIC_ASSERT(sizeof(struct QuadBlock) == MAIN_CANONICAL_TOPOLOGY_LAYOUT_QUAD_BLOCK_BYTES);
CTR_STATIC_ASSERT(offsetof(struct QuadBlock, index) == MAIN_CANONICAL_TOPOLOGY_LAYOUT_QUAD_BLOCK_INDEX_OFFSET);
CTR_STATIC_ASSERT(offsetof(struct QuadBlock, checkpointIndex) == MAIN_CANONICAL_TOPOLOGY_LAYOUT_QUAD_BLOCK_CHECKPOINT_OFFSET);

CTR_STATIC_ASSERT(sizeof(struct mesh_info) == MAIN_CANONICAL_TOPOLOGY_LAYOUT_MESH_INFO_BYTES);
CTR_STATIC_ASSERT(offsetof(struct mesh_info, numQuadBlock) == MAIN_CANONICAL_TOPOLOGY_LAYOUT_MESH_INFO_QUAD_COUNT_OFFSET);
CTR_STATIC_ASSERT(offsetof(struct mesh_info, ptrQuadBlockArray) == MAIN_CANONICAL_TOPOLOGY_LAYOUT_MESH_INFO_QUAD_ARRAY_OFFSET);

CTR_STATIC_ASSERT(sizeof(struct CheckpointNode) == MAIN_CANONICAL_TOPOLOGY_LAYOUT_CHECKPOINT_NODE_BYTES);
CTR_STATIC_ASSERT(offsetof(struct CheckpointNode, pos) == MAIN_CANONICAL_TOPOLOGY_LAYOUT_CHECKPOINT_NODE_POSITION_OFFSET);
CTR_STATIC_ASSERT(offsetof(struct CheckpointNode, distToFinish) == MAIN_CANONICAL_TOPOLOGY_LAYOUT_CHECKPOINT_NODE_DISTANCE_OFFSET);
CTR_STATIC_ASSERT(offsetof(struct CheckpointNode, nextIndex_forward) == MAIN_CANONICAL_TOPOLOGY_LAYOUT_CHECKPOINT_NODE_FORWARD_OFFSET);
CTR_STATIC_ASSERT(offsetof(struct CheckpointNode, nextIndex_right) == MAIN_CANONICAL_TOPOLOGY_LAYOUT_CHECKPOINT_NODE_RIGHT_OFFSET);

CTR_STATIC_ASSERT(sizeof(struct NavFrame) == MAIN_CANONICAL_TOPOLOGY_LAYOUT_NAV_FRAME_BYTES);
CTR_STATIC_ASSERT(offsetof(struct NavFrame, pos) == MAIN_CANONICAL_TOPOLOGY_LAYOUT_NAV_FRAME_POSITION_OFFSET);
CTR_STATIC_ASSERT(offsetof(struct NavFrame, rot) == MAIN_CANONICAL_TOPOLOGY_LAYOUT_NAV_FRAME_ROTATION_OFFSET);
CTR_STATIC_ASSERT(offsetof(struct NavFrame, distToNextNavXYZ) == MAIN_CANONICAL_TOPOLOGY_LAYOUT_NAV_FRAME_DISTANCE_XYZ_OFFSET);
CTR_STATIC_ASSERT(offsetof(struct NavFrame, distToNextNavXZ) == MAIN_CANONICAL_TOPOLOGY_LAYOUT_NAV_FRAME_DISTANCE_XZ_OFFSET);
CTR_STATIC_ASSERT(offsetof(struct NavFrame, flags) == MAIN_CANONICAL_TOPOLOGY_LAYOUT_NAV_FRAME_FLAGS_OFFSET);
CTR_STATIC_ASSERT(offsetof(struct NavFrame, pathChangeOpcode) == MAIN_CANONICAL_TOPOLOGY_LAYOUT_NAV_FRAME_PATH_CHANGE_OFFSET);
CTR_STATIC_ASSERT(offsetof(struct NavFrame, goBackCount) == MAIN_CANONICAL_TOPOLOGY_LAYOUT_NAV_FRAME_GO_BACK_OFFSET);
CTR_STATIC_ASSERT(offsetof(struct NavFrame, specialBits) == MAIN_CANONICAL_TOPOLOGY_LAYOUT_NAV_FRAME_SPECIAL_BITS_OFFSET);

CTR_STATIC_ASSERT(sizeof(struct NavHeader) == MAIN_CANONICAL_TOPOLOGY_LAYOUT_NAV_HEADER_BYTES);
CTR_STATIC_ASSERT(offsetof(struct NavHeader, magicNumber) == MAIN_CANONICAL_TOPOLOGY_LAYOUT_NAV_HEADER_MAGIC_OFFSET);
CTR_STATIC_ASSERT(offsetof(struct NavHeader, numPoints) == MAIN_CANONICAL_TOPOLOGY_LAYOUT_NAV_HEADER_POINT_COUNT_OFFSET);
CTR_STATIC_ASSERT(offsetof(struct NavHeader, posY_firstNode) == MAIN_CANONICAL_TOPOLOGY_LAYOUT_NAV_HEADER_FIRST_POSITION_Y_OFFSET);
CTR_STATIC_ASSERT(offsetof(struct NavHeader, last) == MAIN_CANONICAL_TOPOLOGY_LAYOUT_NAV_HEADER_LAST_OFFSET);
CTR_STATIC_ASSERT(offsetof(struct NavHeader, rampPhys1) == MAIN_CANONICAL_TOPOLOGY_LAYOUT_NAV_HEADER_RAMP_PHYS_1_OFFSET);
CTR_STATIC_ASSERT(offsetof(struct NavHeader, rampPhys2) == MAIN_CANONICAL_TOPOLOGY_LAYOUT_NAV_HEADER_RAMP_PHYS_2_OFFSET);

CTR_STATIC_ASSERT(offsetof(struct Level, ptr_mesh_info) == MAIN_CANONICAL_TOPOLOGY_LAYOUT_LEVEL_MESH_OFFSET);
CTR_STATIC_ASSERT(offsetof(struct Level, cnt_restart_points) == MAIN_CANONICAL_TOPOLOGY_LAYOUT_LEVEL_RESTART_COUNT_OFFSET);
CTR_STATIC_ASSERT(offsetof(struct Level, ptr_restart_points) == MAIN_CANONICAL_TOPOLOGY_LAYOUT_LEVEL_RESTART_POINTS_OFFSET);
CTR_STATIC_ASSERT(offsetof(struct Level, LevNavTable) == MAIN_CANONICAL_TOPOLOGY_LAYOUT_LEVEL_NAV_TABLE_OFFSET);

#endif
